with
daily_weekly_payments_cte as (
	SELECT `Account ID`, `CUSTOMER ID`, PAYMENT_DATE, `ACCOUNT REF`, `PAYMENT ID`, `PAYMENT REF`, 
	LOAN_CREATED_AT_DATE, ORIGINAL_Maturity_DATE, Loan_Purchase_Date, 
	DAILY_EXPECTED_CASH_PAYMENT, DAILY_ACTUAL_CASH_PAYMENTS, DAILY_CREDITS_OTHER, 
	DAILY_INSURANCE_CREDITS, DAILY_PENALTY_CREDITS, CUMULATIVE_CASH_PAYMENTS, 
	CUMULATIVE_CREDITS_OTHER, CUMULATIVE_INSURANCE_CREDITS, CUMULATIVE_PENALTY_CREDITS, `CUMULATIVE CASH + INSURANCE + OTHER + PENALTY`, `MPESA Statement Bank Credit`, 
	BALANCE, DISBURSED_LIABILITY_AT_CUTOFF_DATE, `SC COMMENT`
	FROM kaleidofin_partner_data.daily_weekly_payments
	)
select #*
#distinct PAYMENT_DATE,
#min(PAYMENT_DATE),
#sum(DAILY_ACTUAL_CASH_PAYMENTS)
from daily_weekly_payments_cte
where date(PAYMENT_DATE) = '2026-07-22'
#group by 1
#order by 1 desc