from dotenv import load_dotenv
import os
import requests
import time
from datetime import datetime, timedelta
import psycopg2
from psycopg2.extras import execute_batch
import traceback

# Load environment variables from .env file
load_dotenv()

# Retrieve credentials
sf_client_id = os.getenv("sf_client_id")
sf_client_secret = os.getenv("sf_client_secret")
sf_username = os.getenv("sf_username")
sf_password = os.getenv("sf_password")

# print("Client ID:", sf_client_id)  # Debugging: Check if value is loaded

# Salesforce Authentication URL
sf_instance_url = os.getenv("sf_instance_url")

# Global variable to store access token and expiry time
access_token = None
token_expiry = None

# Database connection parameters
chatbot_db_params = {
    "dbname": os.getenv("chatbot_db"),
    "user": os.getenv("chatbot_db_user"),
    "password": os.getenv("chatbot_db_password"),
    "host": os.getenv("chatbot_db_host"),
    "port": os.getenv("chatbot_db_port")
}

def get_salesforce_token():
    """Fetch OAuth token from Salesforce."""
    sf_auth_url="https://login.salesforce.com/services/oauth2/token"
    payload = {
        "grant_type": "password",
        "client_id": sf_client_id,
        "client_secret": sf_client_secret,
        "username": sf_username,
        "password": sf_password, 
    }
    response = requests.post(sf_auth_url, data=payload)
    #return response.json()["access_token"]
    if response.status_code == 200:
        data = response.json()
        access_token = data.get("access_token")
        instance_url = data.get("instance_url")  # Get dynamically
        print("Salesforce Access Token:", access_token)
        return access_token, instance_url  # Return both
    else:
        print("Error:", response.status_code, response.text)
        return None

def fetch_salesforce_cds_data(access_token, instance_url):
    """Fetch CDS from Salesforce."""
    headers = {"Authorization": f"Bearer {access_token}"}
    query = """
    SELECT Id,
OwnerId,
IsDeleted,
Name,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
LastActivityDate,
LastViewedDate,
LastReferencedDate,
Number_of_Cows__c,
Number_of_Goats__c,
Been_living_in_the_same_location_for__c,
Next_of_Kin_Name__c,
Next_of_Kin_Surname__c,
Number_of_Pigs__c,
Share_name_phone_of_next_of_kin__c,
Next_of_Kin_Phone_Number__c,
Number_of_Sheep__c,
Sales_Manager__c,
Lead_Name__c,
Account__c,
Own_the_land_for_product_installation__c,
How_long_have_you_been_a_farmer__c,
Do_you_have_animals__c,
RM_No_Sales_Telesales_Dealer_Agent__c,
Type_of_fruits_and_vegetables_grown__c,
Pest_disease_control_pest_type_usage__c,
Other_machinery_and_equipment_ownership__c,
Salary_amount__c,
Main_purpose_of_acquiring_the_product__c,
Primary_decision_maker_to_buy_product__c,
Main_source_of_income__c,
Periodicity_of_payment__c,
Compensation_for_the_help_provided__c,
Duration_of_this_activity__c,
Total_amount_from_pension__c,
Total_amount_from_salary_government__c,
Credit_Check_Result__c,
Other_sources_of_income_of_the_household__c,
Credit_Score__c,
Rate_how_well_the_SA_was_able_to_educate__c,
of_Kenyans_that_pay_suppliers_on_time__c,
of_Kenyans_ever_defaulted_on_a_loan__c,
What_would_you_do_if_you_win_Ksh100_000__c,
Overall_Risk_Assessment__c,
Relation_Manager__c,
Types_of_crops_grown__c,
National_ID_Number_Lead__c,
House_Members_F__c,
Gender_Lead__c,
Mobile_Lead__c,
How_long_have_you_had_the_same_phone_No__c,
Email_Address_Lead__c,
County_in_which_HouseHold_resides__c,
Living_in_the_same_location_for__c,
Relation_with_next_of_kin__c,
Number_of_Household_Members__c,
Product_Lead__c,
Ready_to_make_the_deposit_on__c,
Amount_left_after_monthly_expenses__c,
Type_of_crops_grown__c,
Crop_Grown__c,
Wheat_sale__c,
Maize_sale__c,
Paddy_sale__c,
Irish_potatoes_sale__c,
Cassava_sale__c,
Beans_sale__c,
Sunflower_sale__c,
Groundnuts_sale__c,
Other_stable_field_crops_sale__c,
Wheat_self_consumption__c,
Maize_self_consumption__c,
Paddy_self_consumption__c,
Irish_potatoes_self_consumption__c,
Cassava_self_consumption__c,
Beans_self_consumption__c,
Sunflower_self_consumption__c,
Groundnuts_self_consumption__c,
Other_staple_field_crop_self_consumption__c,
Tomatoes_sale__c,
Cabbage_sale__c,
Spinach_sale__c,
Onion_sale__c,
Green_beans_sale__c,
Other_fruits_and_vegetable_sale__c,
Tomatoes_self_consumption__c,
Cabbage_self_consumption__c,
Spinach_self_consumption__c,
Onion_self_consumption__c,
Green_Beans_self_consumption__c,
Other_fruit_vegetable_self_consumption__c,
Harvest_Cycle_Per_Year__c,
Same_number_as_provided_in_CDS1__c,
Recall_the_call__c,
Farm_acreage__c,
Main_Purpose_of_acquiring_the_pump__c,
How_did_you_hear_about_SunCulture_pumps__c,
Other_sources_of_water__c,
Hours_spent_fetching_water_every_week__c,
Amount_paid_for_getting_water_each_week__c,
Amount_paid_for_water_other_pump_usage__c,
Customer_Data_Survey_Number__c,
Quantity_of_water_usage_per_week__c,
Water_tank_capacity__c,
Electricity_connectivity__c,
Number_of_financial_dependants__c,
Number_of_working_age_adults_in_the_HH__c,
Number_of_pensioners_living_in_the_HH__c,
No_of_family_members_friends_helping__c,
Number_of_businesses_before__c,
Average_monthly_income__c,
Understand_the_products_shared_with_you__c,
No_of_years_working_with_same_employer__c,
No_of_jobs_in_the_last_5yrs__c,
Total_amount_from_remittances__c,
Total_amount_from_Agriculture__c,
Total_amount_from_commerce_and_trade__c,
Total_Amt_from_salary_private_inst__c,
Total_amount_from_provision_of_services__c,
Agent_seek_to_understand_how_you_source__c,
Amount_spent_on_school_fees__c,
Amount_spent_on_food__c,
Amount_spent_on_farm_inputs__c,
Amount_spent_on_rent__c,
Amount_spent_on_loans__c,
Amount_spent_on_other__c,
Currently_have_any_outstanding_loans__c,
Total_amount_of_outstanding_loan_s__c,
No_of_months_to_finish_paying_loan_s__c,
Preferred_banking_method__c,
World_perception_supplier__c,
World_perception_default__c,
Number_of_loans_taken_in_the_last_2yrs__c,
Periodicity_of_the_income__c,
Like_further_clarification_on_our_Prod__c,
Likelihood_to_recommend_our_Prod__c,
Name_Number_of_the_recommend_client__c,
Agent__c,
Survey_Completed__c,
Duration_with_same_employer_5yrs_F__c,
water_source_river__c,
Stage__c,
Account_Number__c,
Gender_Male_F__c,
World_perception_supplier_6080_F__c,
Overall_Risk_Assessment_Low_Risk_F__c,
Other_sources_of_water_river_F__c,
Other_sources_of_water_Borehole_F__c,
Do_you_have_animals_4F__c,
Do_you_have_animals_3F__c,
Types_of_crops_grown_1_type_F__c,
Type_of_fruits_and_vegetables_grown_4F__c,
Type_of_fruits_and_vegetables_grown_0F__c,
CDS1Tracker__c,
Birth_Date__c,
Date_of_Birth_46_55yrs_F__c,
Date_of_Birth_older_than_55yrs_F__c,
Hear_about_SunCulture_pumps_Online_F__c,
Hear_about_SunCulture_pumps_Radio_F__c,
Other_Sources_of_HH_Income_Pension_F__c,
Date_of_Birth__c,
Email__c,
National_ID_Number__c,
Gender__c,
Mobile_Number__c,
Working_age_adults_F__c,
Harvest_Cycle_F__c,
RM_Name__c,
cds_source__c,
Did_you_previously_own_a_water_pump__c,
carbon_credit_which_pump_type__c,
CDS1_Date__c,
CDS2_Date__c,
Number_of_Outstanding_Loans__c,
Depth_of_the_Water_Source__c,
Total_Income__c,
Total_Expenses__c,
Remaining_Income_after_Expenses__c,
Lead_Record__c,
Creditscore__c,
Clients_County_Ug__c,
Clients_District__c,
Clients_Nearest_Landmark__c,
Clients_Parish__c,
Clients_Sub_County__c,
Clients_Village_ug__c,
Amount_Spent_on_Treatment_Medical__c,
Reason_for_decline__c,
Seasonality_of_the_Water_Source__c,
Product__c
    FROM Customer_Data_Survey__c
    """
    all_cds = []
    next_url = f"{instance_url}/services/data/v58.0/query?q={query}"
    
    while next_url:
        response = requests.get(next_url, headers=headers)
        if response.status_code == 200:
            data = response.json()
            all_cds.extend(data.get("records", []))
            next_url = f"{instance_url}{data.get('nextRecordsUrl')}" if "nextRecordsUrl" in data else None
            time.sleep(1)  # Add a 1-second delay
        else:
            print("Failed to fetch CDS:", response.text)
            break
    return all_cds

def save_sf_cds_data_to_postgres(cds_data):
    """Save CDS to PostgreSQL."""
    db_connection = psycopg2.connect(**chatbot_db_params)
    cursor = db_connection.cursor()
    
    # Upsert query (adjust fields based on your schema)
    query = """
    INSERT INTO sf_cds (
        Id,
OwnerId,
IsDeleted,
Name,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
LastActivityDate,
LastViewedDate,
LastReferencedDate,
Number_of_Cows__c,
Number_of_Goats__c,
Been_living_in_the_same_location_for__c,
Next_of_Kin_Name__c,
Next_of_Kin_Surname__c,
Number_of_Pigs__c,
Share_name_phone_of_next_of_kin__c,
Next_of_Kin_Phone_Number__c,
Number_of_Sheep__c,
Sales_Manager__c,
Lead_Name__c,
Account__c,
Own_the_land_for_product_installation__c,
How_long_have_you_been_a_farmer__c,
Do_you_have_animals__c,
RM_No_Sales_Telesales_Dealer_Agent__c,
Type_of_fruits_and_vegetables_grown__c,
Pest_disease_control_pest_type_usage__c,
Other_machinery_and_equipment_ownership__c,
Salary_amount__c,
Main_purpose_of_acquiring_the_product__c,
Primary_decision_maker_to_buy_product__c,
Main_source_of_income__c,
Periodicity_of_payment__c,
Compensation_for_the_help_provided__c,
Duration_of_this_activity__c,
Total_amount_from_pension__c,
Total_amount_from_salary_government__c,
Credit_Check_Result__c,
Other_sources_of_income_of_the_household__c,
Credit_Score__c,
Rate_how_well_the_SA_was_able_to_educate__c,
of_Kenyans_that_pay_suppliers_on_time__c,
of_Kenyans_ever_defaulted_on_a_loan__c,
What_would_you_do_if_you_win_Ksh100_000__c,
Overall_Risk_Assessment__c,
Relation_Manager__c,
Types_of_crops_grown__c,
National_ID_Number_Lead__c,
House_Members_F__c,
Gender_Lead__c,
Mobile_Lead__c,
How_long_have_you_had_the_same_phone_No__c,
Email_Address_Lead__c,
County_in_which_HouseHold_resides__c,
Living_in_the_same_location_for__c,
Relation_with_next_of_kin__c,
Number_of_Household_Members__c,
Product_Lead__c,
Ready_to_make_the_deposit_on__c,
Amount_left_after_monthly_expenses__c,
Type_of_crops_grown__c,
Crop_Grown__c,
Wheat_sale__c,
Maize_sale__c,
Paddy_sale__c,
Irish_potatoes_sale__c,
Cassava_sale__c,
Beans_sale__c,
Sunflower_sale__c,
Groundnuts_sale__c,
Other_stable_field_crops_sale__c,
Wheat_self_consumption__c,
Maize_self_consumption__c,
Paddy_self_consumption__c,
Irish_potatoes_self_consumption__c,
Cassava_self_consumption__c,
Beans_self_consumption__c,
Sunflower_self_consumption__c,
Groundnuts_self_consumption__c,
Other_staple_field_crop_self_consumption__c,
Tomatoes_sale__c,
Cabbage_sale__c,
Spinach_sale__c,
Onion_sale__c,
Green_beans_sale__c,
Other_fruits_and_vegetable_sale__c,
Tomatoes_self_consumption__c,
Cabbage_self_consumption__c,
Spinach_self_consumption__c,
Onion_self_consumption__c,
Green_Beans_self_consumption__c,
Other_fruit_vegetable_self_consumption__c,
Harvest_Cycle_Per_Year__c,
Same_number_as_provided_in_CDS1__c,
Recall_the_call__c,
Farm_acreage__c,
Main_Purpose_of_acquiring_the_pump__c,
How_did_you_hear_about_SunCulture_pumps__c,
Other_sources_of_water__c,
Hours_spent_fetching_water_every_week__c,
Amount_paid_for_getting_water_each_week__c,
Amount_paid_for_water_other_pump_usage__c,
Customer_Data_Survey_Number__c,
Quantity_of_water_usage_per_week__c,
Water_tank_capacity__c,
Electricity_connectivity__c,
Number_of_financial_dependants__c,
Number_of_working_age_adults_in_the_HH__c,
Number_of_pensioners_living_in_the_HH__c,
No_of_family_members_friends_helping__c,
Number_of_businesses_before__c,
Average_monthly_income__c,
Understand_the_products_shared_with_you__c,
No_of_years_working_with_same_employer__c,
No_of_jobs_in_the_last_5yrs__c,
Total_amount_from_remittances__c,
Total_amount_from_Agriculture__c,
Total_amount_from_commerce_and_trade__c,
Total_Amt_from_salary_private_inst__c,
Total_amount_from_provision_of_services__c,
Agent_seek_to_understand_how_you_source__c,
Amount_spent_on_school_fees__c,
Amount_spent_on_food__c,
Amount_spent_on_farm_inputs__c,
Amount_spent_on_rent__c,
Amount_spent_on_loans__c,
Amount_spent_on_other__c,
Currently_have_any_outstanding_loans__c,
Total_amount_of_outstanding_loan_s__c,
No_of_months_to_finish_paying_loan_s__c,
Preferred_banking_method__c,
World_perception_supplier__c,
World_perception_default__c,
Number_of_loans_taken_in_the_last_2yrs__c,
Periodicity_of_the_income__c,
Like_further_clarification_on_our_Prod__c,
Likelihood_to_recommend_our_Prod__c,
Name_Number_of_the_recommend_client__c,
Agent__c,
Survey_Completed__c,
Duration_with_same_employer_5yrs_F__c,
water_source_river__c,
Stage__c,
Account_Number__c,
Gender_Male_F__c,
World_perception_supplier_6080_F__c,
Overall_Risk_Assessment_Low_Risk_F__c,
Other_sources_of_water_river_F__c,
Other_sources_of_water_Borehole_F__c,
Do_you_have_animals_4F__c,
Do_you_have_animals_3F__c,
Types_of_crops_grown_1_type_F__c,
Type_of_fruits_and_vegetables_grown_4F__c,
Type_of_fruits_and_vegetables_grown_0F__c,
CDS1Tracker__c,
Birth_Date__c,
Date_of_Birth_46_55yrs_F__c,
Date_of_Birth_older_than_55yrs_F__c,
Hear_about_SunCulture_pumps_Online_F__c,
Hear_about_SunCulture_pumps_Radio_F__c,
Other_Sources_of_HH_Income_Pension_F__c,
Date_of_Birth__c,
Email__c,
National_ID_Number__c,
Gender__c,
Mobile_Number__c,
Working_age_adults_F__c,
Harvest_Cycle_F__c,
RM_Name__c,
cds_source__c,
Did_you_previously_own_a_water_pump__c,
carbon_credit_which_pump_type__c,
CDS1_Date__c,
CDS2_Date__c,
Number_of_Outstanding_Loans__c,
Depth_of_the_Water_Source__c,
Total_Income__c,
Total_Expenses__c,
Remaining_Income_after_Expenses__c,
Lead_Record__c,
Creditscore__c,
Clients_County_Ug__c,
Clients_District__c,
Clients_Nearest_Landmark__c,
Clients_Parish__c,
Clients_Sub_County__c,
Clients_Village_ug__c,
Amount_Spent_on_Treatment_Medical__c,
Reason_for_decline__c,
Seasonality_of_the_Water_Source__c,
Product__c
    )
    VALUES (
        %(Id)s,
%(OwnerId)s,
%(IsDeleted)s,
%(Name)s,
%(CreatedDate)s,
%(CreatedById)s,
%(LastModifiedDate)s,
%(LastModifiedById)s,
%(SystemModstamp)s,
%(LastActivityDate)s,
%(LastViewedDate)s,
%(LastReferencedDate)s,
%(Number_of_Cows__c)s,
%(Number_of_Goats__c)s,
%(Been_living_in_the_same_location_for__c)s,
%(Next_of_Kin_Name__c)s,
%(Next_of_Kin_Surname__c)s,
%(Number_of_Pigs__c)s,
%(Share_name_phone_of_next_of_kin__c)s,
%(Next_of_Kin_Phone_Number__c)s,
%(Number_of_Sheep__c)s,
%(Sales_Manager__c)s,
%(Lead_Name__c)s,
%(Account__c)s,
%(Own_the_land_for_product_installation__c)s,
%(How_long_have_you_been_a_farmer__c)s,
%(Do_you_have_animals__c)s,
%(RM_No_Sales_Telesales_Dealer_Agent__c)s,
%(Type_of_fruits_and_vegetables_grown__c)s,
%(Pest_disease_control_pest_type_usage__c)s,
%(Other_machinery_and_equipment_ownership__c)s,
%(Salary_amount__c)s,
%(Main_purpose_of_acquiring_the_product__c)s,
%(Primary_decision_maker_to_buy_product__c)s,
%(Main_source_of_income__c)s,
%(Periodicity_of_payment__c)s,
%(Compensation_for_the_help_provided__c)s,
%(Duration_of_this_activity__c)s,
%(Total_amount_from_pension__c)s,
%(Total_amount_from_salary_government__c)s,
%(Credit_Check_Result__c)s,
%(Other_sources_of_income_of_the_household__c)s,
%(Credit_Score__c)s,
%(Rate_how_well_the_SA_was_able_to_educate__c)s,
%(of_Kenyans_that_pay_suppliers_on_time__c)s,
%(of_Kenyans_ever_defaulted_on_a_loan__c)s,
%(What_would_you_do_if_you_win_Ksh100_000__c)s,
%(Overall_Risk_Assessment__c)s,
%(Relation_Manager__c)s,
%(Types_of_crops_grown__c)s,
%(National_ID_Number_Lead__c)s,
%(House_Members_F__c)s,
%(Gender_Lead__c)s,
%(Mobile_Lead__c)s,
%(How_long_have_you_had_the_same_phone_No__c)s,
%(Email_Address_Lead__c)s,
%(County_in_which_HouseHold_resides__c)s,
%(Living_in_the_same_location_for__c)s,
%(Relation_with_next_of_kin__c)s,
%(Number_of_Household_Members__c)s,
%(Product_Lead__c)s,
%(Ready_to_make_the_deposit_on__c)s,
%(Amount_left_after_monthly_expenses__c)s,
%(Type_of_crops_grown__c)s,
%(Crop_Grown__c)s,
%(Wheat_sale__c)s,
%(Maize_sale__c)s,
%(Paddy_sale__c)s,
%(Irish_potatoes_sale__c)s,
%(Cassava_sale__c)s,
%(Beans_sale__c)s,
%(Sunflower_sale__c)s,
%(Groundnuts_sale__c)s,
%(Other_stable_field_crops_sale__c)s,
%(Wheat_self_consumption__c)s,
%(Maize_self_consumption__c)s,
%(Paddy_self_consumption__c)s,
%(Irish_potatoes_self_consumption__c)s,
%(Cassava_self_consumption__c)s,
%(Beans_self_consumption__c)s,
%(Sunflower_self_consumption__c)s,
%(Groundnuts_self_consumption__c)s,
%(Other_staple_field_crop_self_consumption__c)s,
%(Tomatoes_sale__c)s,
%(Cabbage_sale__c)s,
%(Spinach_sale__c)s,
%(Onion_sale__c)s,
%(Green_beans_sale__c)s,
%(Other_fruits_and_vegetable_sale__c)s,
%(Tomatoes_self_consumption__c)s,
%(Cabbage_self_consumption__c)s,
%(Spinach_self_consumption__c)s,
%(Onion_self_consumption__c)s,
%(Green_Beans_self_consumption__c)s,
%(Other_fruit_vegetable_self_consumption__c)s,
%(Harvest_Cycle_Per_Year__c)s,
%(Same_number_as_provided_in_CDS1__c)s,
%(Recall_the_call__c)s,
%(Farm_acreage__c)s,
%(Main_Purpose_of_acquiring_the_pump__c)s,
%(How_did_you_hear_about_SunCulture_pumps__c)s,
%(Other_sources_of_water__c)s,
%(Hours_spent_fetching_water_every_week__c)s,
%(Amount_paid_for_getting_water_each_week__c)s,
%(Amount_paid_for_water_other_pump_usage__c)s,
%(Customer_Data_Survey_Number__c)s,
%(Quantity_of_water_usage_per_week__c)s,
%(Water_tank_capacity__c)s,
%(Electricity_connectivity__c)s,
%(Number_of_financial_dependants__c)s,
%(Number_of_working_age_adults_in_the_HH__c)s,
%(Number_of_pensioners_living_in_the_HH__c)s,
%(No_of_family_members_friends_helping__c)s,
%(Number_of_businesses_before__c)s,
%(Average_monthly_income__c)s,
%(Understand_the_products_shared_with_you__c)s,
%(No_of_years_working_with_same_employer__c)s,
%(No_of_jobs_in_the_last_5yrs__c)s,
%(Total_amount_from_remittances__c)s,
%(Total_amount_from_Agriculture__c)s,
%(Total_amount_from_commerce_and_trade__c)s,
%(Total_Amt_from_salary_private_inst__c)s,
%(Total_amount_from_provision_of_services__c)s,
%(Agent_seek_to_understand_how_you_source__c)s,
%(Amount_spent_on_school_fees__c)s,
%(Amount_spent_on_food__c)s,
%(Amount_spent_on_farm_inputs__c)s,
%(Amount_spent_on_rent__c)s,
%(Amount_spent_on_loans__c)s,
%(Amount_spent_on_other__c)s,
%(Currently_have_any_outstanding_loans__c)s,
%(Total_amount_of_outstanding_loan_s__c)s,
%(No_of_months_to_finish_paying_loan_s__c)s,
%(Preferred_banking_method__c)s,
%(World_perception_supplier__c)s,
%(World_perception_default__c)s,
%(Number_of_loans_taken_in_the_last_2yrs__c)s,
%(Periodicity_of_the_income__c)s,
%(Like_further_clarification_on_our_Prod__c)s,
%(Likelihood_to_recommend_our_Prod__c)s,
%(Name_Number_of_the_recommend_client__c)s,
%(Agent__c)s,
%(Survey_Completed__c)s,
%(Duration_with_same_employer_5yrs_F__c)s,
%(water_source_river__c)s,
%(Stage__c)s,
%(Account_Number__c)s,
%(Gender_Male_F__c)s,
%(World_perception_supplier_6080_F__c)s,
%(Overall_Risk_Assessment_Low_Risk_F__c)s,
%(Other_sources_of_water_river_F__c)s,
%(Other_sources_of_water_Borehole_F__c)s,
%(Do_you_have_animals_4F__c)s,
%(Do_you_have_animals_3F__c)s,
%(Types_of_crops_grown_1_type_F__c)s,
%(Type_of_fruits_and_vegetables_grown_4F__c)s,
%(Type_of_fruits_and_vegetables_grown_0F__c)s,
%(CDS1Tracker__c)s,
%(Birth_Date__c)s,
%(Date_of_Birth_46_55yrs_F__c)s,
%(Date_of_Birth_older_than_55yrs_F__c)s,
%(Hear_about_SunCulture_pumps_Online_F__c)s,
%(Hear_about_SunCulture_pumps_Radio_F__c)s,
%(Other_Sources_of_HH_Income_Pension_F__c)s,
%(Date_of_Birth__c)s,
%(Email__c)s,
%(National_ID_Number__c)s,
%(Gender__c)s,
%(Mobile_Number__c)s,
%(Working_age_adults_F__c)s,
%(Harvest_Cycle_F__c)s,
%(RM_Name__c)s,
%(cds_source__c)s,
%(Did_you_previously_own_a_water_pump__c)s,
%(carbon_credit_which_pump_type__c)s,
%(CDS1_Date__c)s,
%(CDS2_Date__c)s,
%(Number_of_Outstanding_Loans__c)s,
%(Depth_of_the_Water_Source__c)s,
%(Total_Income__c)s,
%(Total_Expenses__c)s,
%(Remaining_Income_after_Expenses__c)s,
%(Lead_Record__c)s,
%(Creditscore__c)s,
%(Clients_County_Ug__c)s,
%(Clients_District__c)s,
%(Clients_Nearest_Landmark__c)s,
%(Clients_Parish__c)s,
%(Clients_Sub_County__c)s,
%(Clients_Village_ug__c)s,
%(Amount_Spent_on_Treatment_Medical__c)s,
%(Reason_for_decline__c)s,
%(Seasonality_of_the_Water_Source__c)s,
%(Product__c)s
    )
    ON CONFLICT (Id) 
    DO UPDATE SET 
    OwnerId = Excluded.OwnerId,
IsDeleted = Excluded.IsDeleted,
Name = Excluded.Name,
CreatedDate = Excluded.CreatedDate,
CreatedById = Excluded.CreatedById,
LastModifiedDate = Excluded.LastModifiedDate,
LastModifiedById = Excluded.LastModifiedById,
SystemModstamp = Excluded.SystemModstamp,
LastActivityDate = Excluded.LastActivityDate,
LastViewedDate = Excluded.LastViewedDate,
LastReferencedDate = Excluded.LastReferencedDate,
Number_of_Cows__c = Excluded.Number_of_Cows__c,
Number_of_Goats__c = Excluded.Number_of_Goats__c,
Been_living_in_the_same_location_for__c = Excluded.Been_living_in_the_same_location_for__c,
Next_of_Kin_Name__c = Excluded.Next_of_Kin_Name__c,
Next_of_Kin_Surname__c = Excluded.Next_of_Kin_Surname__c,
Number_of_Pigs__c = Excluded.Number_of_Pigs__c,
Share_name_phone_of_next_of_kin__c = Excluded.Share_name_phone_of_next_of_kin__c,
Next_of_Kin_Phone_Number__c = Excluded.Next_of_Kin_Phone_Number__c,
Number_of_Sheep__c = Excluded.Number_of_Sheep__c,
Sales_Manager__c = Excluded.Sales_Manager__c,
Lead_Name__c = Excluded.Lead_Name__c,
Account__c = Excluded.Account__c,
Own_the_land_for_product_installation__c = Excluded.Own_the_land_for_product_installation__c,
How_long_have_you_been_a_farmer__c = Excluded.How_long_have_you_been_a_farmer__c,
Do_you_have_animals__c = Excluded.Do_you_have_animals__c,
RM_No_Sales_Telesales_Dealer_Agent__c = Excluded.RM_No_Sales_Telesales_Dealer_Agent__c,
Type_of_fruits_and_vegetables_grown__c = Excluded.Type_of_fruits_and_vegetables_grown__c,
Pest_disease_control_pest_type_usage__c = Excluded.Pest_disease_control_pest_type_usage__c,
Other_machinery_and_equipment_ownership__c = Excluded.Other_machinery_and_equipment_ownership__c,
Salary_amount__c = Excluded.Salary_amount__c,
Main_purpose_of_acquiring_the_product__c = Excluded.Main_purpose_of_acquiring_the_product__c,
Primary_decision_maker_to_buy_product__c = Excluded.Primary_decision_maker_to_buy_product__c,
Main_source_of_income__c = Excluded.Main_source_of_income__c,
Periodicity_of_payment__c = Excluded.Periodicity_of_payment__c,
Compensation_for_the_help_provided__c = Excluded.Compensation_for_the_help_provided__c,
Duration_of_this_activity__c = Excluded.Duration_of_this_activity__c,
Total_amount_from_pension__c = Excluded.Total_amount_from_pension__c,
Total_amount_from_salary_government__c = Excluded.Total_amount_from_salary_government__c,
Credit_Check_Result__c = Excluded.Credit_Check_Result__c,
Other_sources_of_income_of_the_household__c = Excluded.Other_sources_of_income_of_the_household__c,
Credit_Score__c = Excluded.Credit_Score__c,
Rate_how_well_the_SA_was_able_to_educate__c = Excluded.Rate_how_well_the_SA_was_able_to_educate__c,
of_Kenyans_that_pay_suppliers_on_time__c = Excluded.of_Kenyans_that_pay_suppliers_on_time__c,
of_Kenyans_ever_defaulted_on_a_loan__c = Excluded.of_Kenyans_ever_defaulted_on_a_loan__c,
What_would_you_do_if_you_win_Ksh100_000__c = Excluded.What_would_you_do_if_you_win_Ksh100_000__c,
Overall_Risk_Assessment__c = Excluded.Overall_Risk_Assessment__c,
Relation_Manager__c = Excluded.Relation_Manager__c,
Types_of_crops_grown__c = Excluded.Types_of_crops_grown__c,
National_ID_Number_Lead__c = Excluded.National_ID_Number_Lead__c,
House_Members_F__c = Excluded.House_Members_F__c,
Gender_Lead__c = Excluded.Gender_Lead__c,
Mobile_Lead__c = Excluded.Mobile_Lead__c,
How_long_have_you_had_the_same_phone_No__c = Excluded.How_long_have_you_had_the_same_phone_No__c,
Email_Address_Lead__c = Excluded.Email_Address_Lead__c,
County_in_which_HouseHold_resides__c = Excluded.County_in_which_HouseHold_resides__c,
Living_in_the_same_location_for__c = Excluded.Living_in_the_same_location_for__c,
Relation_with_next_of_kin__c = Excluded.Relation_with_next_of_kin__c,
Number_of_Household_Members__c = Excluded.Number_of_Household_Members__c,
Product_Lead__c = Excluded.Product_Lead__c,
Ready_to_make_the_deposit_on__c = Excluded.Ready_to_make_the_deposit_on__c,
Amount_left_after_monthly_expenses__c = Excluded.Amount_left_after_monthly_expenses__c,
Type_of_crops_grown__c = Excluded.Type_of_crops_grown__c,
Crop_Grown__c = Excluded.Crop_Grown__c,
Wheat_sale__c = Excluded.Wheat_sale__c,
Maize_sale__c = Excluded.Maize_sale__c,
Paddy_sale__c = Excluded.Paddy_sale__c,
Irish_potatoes_sale__c = Excluded.Irish_potatoes_sale__c,
Cassava_sale__c = Excluded.Cassava_sale__c,
Beans_sale__c = Excluded.Beans_sale__c,
Sunflower_sale__c = Excluded.Sunflower_sale__c,
Groundnuts_sale__c = Excluded.Groundnuts_sale__c,
Other_stable_field_crops_sale__c = Excluded.Other_stable_field_crops_sale__c,
Wheat_self_consumption__c = Excluded.Wheat_self_consumption__c,
Maize_self_consumption__c = Excluded.Maize_self_consumption__c,
Paddy_self_consumption__c = Excluded.Paddy_self_consumption__c,
Irish_potatoes_self_consumption__c = Excluded.Irish_potatoes_self_consumption__c,
Cassava_self_consumption__c = Excluded.Cassava_self_consumption__c,
Beans_self_consumption__c = Excluded.Beans_self_consumption__c,
Sunflower_self_consumption__c = Excluded.Sunflower_self_consumption__c,
Groundnuts_self_consumption__c = Excluded.Groundnuts_self_consumption__c,
Other_staple_field_crop_self_consumption__c = Excluded.Other_staple_field_crop_self_consumption__c,
Tomatoes_sale__c = Excluded.Tomatoes_sale__c,
Cabbage_sale__c = Excluded.Cabbage_sale__c,
Spinach_sale__c = Excluded.Spinach_sale__c,
Onion_sale__c = Excluded.Onion_sale__c,
Green_beans_sale__c = Excluded.Green_beans_sale__c,
Other_fruits_and_vegetable_sale__c = Excluded.Other_fruits_and_vegetable_sale__c,
Tomatoes_self_consumption__c = Excluded.Tomatoes_self_consumption__c,
Cabbage_self_consumption__c = Excluded.Cabbage_self_consumption__c,
Spinach_self_consumption__c = Excluded.Spinach_self_consumption__c,
Onion_self_consumption__c = Excluded.Onion_self_consumption__c,
Green_Beans_self_consumption__c = Excluded.Green_Beans_self_consumption__c,
Other_fruit_vegetable_self_consumption__c = Excluded.Other_fruit_vegetable_self_consumption__c,
Harvest_Cycle_Per_Year__c = Excluded.Harvest_Cycle_Per_Year__c,
Same_number_as_provided_in_CDS1__c = Excluded.Same_number_as_provided_in_CDS1__c,
Recall_the_call__c = Excluded.Recall_the_call__c,
Farm_acreage__c = Excluded.Farm_acreage__c,
Main_Purpose_of_acquiring_the_pump__c = Excluded.Main_Purpose_of_acquiring_the_pump__c,
How_did_you_hear_about_SunCulture_pumps__c = Excluded.How_did_you_hear_about_SunCulture_pumps__c,
Other_sources_of_water__c = Excluded.Other_sources_of_water__c,
Hours_spent_fetching_water_every_week__c = Excluded.Hours_spent_fetching_water_every_week__c,
Amount_paid_for_getting_water_each_week__c = Excluded.Amount_paid_for_getting_water_each_week__c,
Amount_paid_for_water_other_pump_usage__c = Excluded.Amount_paid_for_water_other_pump_usage__c,
Customer_Data_Survey_Number__c = Excluded.Customer_Data_Survey_Number__c,
Quantity_of_water_usage_per_week__c = Excluded.Quantity_of_water_usage_per_week__c,
Water_tank_capacity__c = Excluded.Water_tank_capacity__c,
Electricity_connectivity__c = Excluded.Electricity_connectivity__c,
Number_of_financial_dependants__c = Excluded.Number_of_financial_dependants__c,
Number_of_working_age_adults_in_the_HH__c = Excluded.Number_of_working_age_adults_in_the_HH__c,
Number_of_pensioners_living_in_the_HH__c = Excluded.Number_of_pensioners_living_in_the_HH__c,
No_of_family_members_friends_helping__c = Excluded.No_of_family_members_friends_helping__c,
Number_of_businesses_before__c = Excluded.Number_of_businesses_before__c,
Average_monthly_income__c = Excluded.Average_monthly_income__c,
Understand_the_products_shared_with_you__c = Excluded.Understand_the_products_shared_with_you__c,
No_of_years_working_with_same_employer__c = Excluded.No_of_years_working_with_same_employer__c,
No_of_jobs_in_the_last_5yrs__c = Excluded.No_of_jobs_in_the_last_5yrs__c,
Total_amount_from_remittances__c = Excluded.Total_amount_from_remittances__c,
Total_amount_from_Agriculture__c = Excluded.Total_amount_from_Agriculture__c,
Total_amount_from_commerce_and_trade__c = Excluded.Total_amount_from_commerce_and_trade__c,
Total_Amt_from_salary_private_inst__c = Excluded.Total_Amt_from_salary_private_inst__c,
Total_amount_from_provision_of_services__c = Excluded.Total_amount_from_provision_of_services__c,
Agent_seek_to_understand_how_you_source__c = Excluded.Agent_seek_to_understand_how_you_source__c,
Amount_spent_on_school_fees__c = Excluded.Amount_spent_on_school_fees__c,
Amount_spent_on_food__c = Excluded.Amount_spent_on_food__c,
Amount_spent_on_farm_inputs__c = Excluded.Amount_spent_on_farm_inputs__c,
Amount_spent_on_rent__c = Excluded.Amount_spent_on_rent__c,
Amount_spent_on_loans__c = Excluded.Amount_spent_on_loans__c,
Amount_spent_on_other__c = Excluded.Amount_spent_on_other__c,
Currently_have_any_outstanding_loans__c = Excluded.Currently_have_any_outstanding_loans__c,
Total_amount_of_outstanding_loan_s__c = Excluded.Total_amount_of_outstanding_loan_s__c,
No_of_months_to_finish_paying_loan_s__c = Excluded.No_of_months_to_finish_paying_loan_s__c,
Preferred_banking_method__c = Excluded.Preferred_banking_method__c,
World_perception_supplier__c = Excluded.World_perception_supplier__c,
World_perception_default__c = Excluded.World_perception_default__c,
Number_of_loans_taken_in_the_last_2yrs__c = Excluded.Number_of_loans_taken_in_the_last_2yrs__c,
Periodicity_of_the_income__c = Excluded.Periodicity_of_the_income__c,
Like_further_clarification_on_our_Prod__c = Excluded.Like_further_clarification_on_our_Prod__c,
Likelihood_to_recommend_our_Prod__c = Excluded.Likelihood_to_recommend_our_Prod__c,
Name_Number_of_the_recommend_client__c = Excluded.Name_Number_of_the_recommend_client__c,
Agent__c = Excluded.Agent__c,
Survey_Completed__c = Excluded.Survey_Completed__c,
Duration_with_same_employer_5yrs_F__c = Excluded.Duration_with_same_employer_5yrs_F__c,
water_source_river__c = Excluded.water_source_river__c,
Stage__c = Excluded.Stage__c,
Account_Number__c = Excluded.Account_Number__c,
Gender_Male_F__c = Excluded.Gender_Male_F__c,
World_perception_supplier_6080_F__c = Excluded.World_perception_supplier_6080_F__c,
Overall_Risk_Assessment_Low_Risk_F__c = Excluded.Overall_Risk_Assessment_Low_Risk_F__c,
Other_sources_of_water_river_F__c = Excluded.Other_sources_of_water_river_F__c,
Other_sources_of_water_Borehole_F__c = Excluded.Other_sources_of_water_Borehole_F__c,
Do_you_have_animals_4F__c = Excluded.Do_you_have_animals_4F__c,
Do_you_have_animals_3F__c = Excluded.Do_you_have_animals_3F__c,
Types_of_crops_grown_1_type_F__c = Excluded.Types_of_crops_grown_1_type_F__c,
Type_of_fruits_and_vegetables_grown_4F__c = Excluded.Type_of_fruits_and_vegetables_grown_4F__c,
Type_of_fruits_and_vegetables_grown_0F__c = Excluded.Type_of_fruits_and_vegetables_grown_0F__c,
CDS1Tracker__c = Excluded.CDS1Tracker__c,
Birth_Date__c = Excluded.Birth_Date__c,
Date_of_Birth_46_55yrs_F__c = Excluded.Date_of_Birth_46_55yrs_F__c,
Date_of_Birth_older_than_55yrs_F__c = Excluded.Date_of_Birth_older_than_55yrs_F__c,
Hear_about_SunCulture_pumps_Online_F__c = Excluded.Hear_about_SunCulture_pumps_Online_F__c,
Hear_about_SunCulture_pumps_Radio_F__c = Excluded.Hear_about_SunCulture_pumps_Radio_F__c,
Other_Sources_of_HH_Income_Pension_F__c = Excluded.Other_Sources_of_HH_Income_Pension_F__c,
Date_of_Birth__c = Excluded.Date_of_Birth__c,
Email__c = Excluded.Email__c,
National_ID_Number__c = Excluded.National_ID_Number__c,
Gender__c = Excluded.Gender__c,
Mobile_Number__c = Excluded.Mobile_Number__c,
Working_age_adults_F__c = Excluded.Working_age_adults_F__c,
Harvest_Cycle_F__c = Excluded.Harvest_Cycle_F__c,
RM_Name__c = Excluded.RM_Name__c,
cds_source__c = Excluded.cds_source__c,
Did_you_previously_own_a_water_pump__c = Excluded.Did_you_previously_own_a_water_pump__c,
carbon_credit_which_pump_type__c = Excluded.carbon_credit_which_pump_type__c,
CDS1_Date__c = Excluded.CDS1_Date__c,
CDS2_Date__c = Excluded.CDS2_Date__c,
Number_of_Outstanding_Loans__c = Excluded.Number_of_Outstanding_Loans__c,
Depth_of_the_Water_Source__c = Excluded.Depth_of_the_Water_Source__c,
Total_Income__c = Excluded.Total_Income__c,
Total_Expenses__c = Excluded.Total_Expenses__c,
Remaining_Income_after_Expenses__c = Excluded.Remaining_Income_after_Expenses__c,
Lead_Record__c = Excluded.Lead_Record__c,
Creditscore__c = Excluded.Creditscore__c,
Clients_County_Ug__c = Excluded.Clients_County_Ug__c,
Clients_District__c = Excluded.Clients_District__c,
Clients_Nearest_Landmark__c = Excluded.Clients_Nearest_Landmark__c,
Clients_Parish__c = Excluded.Clients_Parish__c,
Clients_Sub_County__c = Excluded.Clients_Sub_County__c,
Clients_Village_ug__c = Excluded.Clients_Village_ug__c,
Amount_Spent_on_Treatment_Medical__c = Excluded.Amount_Spent_on_Treatment_Medical__c,
Reason_for_decline__c = Excluded.Reason_for_decline__c,
Seasonality_of_the_Water_Source__c = Excluded.Seasonality_of_the_Water_Source__c,
Product__c = Excluded.Product__c
    """
    
    try:
        # Prepare data
        data = []
        for cds_record in cds_data:
            # Check each field for length violations
            cds_data = {
                # Map all fields here
                'Id': cds_record.get('Id'),
'OwnerId': cds_record.get('OwnerId'),
'IsDeleted': cds_record.get('IsDeleted'),
'Name': cds_record.get('Name'),
'CreatedDate': cds_record.get('CreatedDate'),
'CreatedById': cds_record.get('CreatedById'),
'LastModifiedDate': cds_record.get('LastModifiedDate'),
'LastModifiedById': cds_record.get('LastModifiedById'),
'SystemModstamp': cds_record.get('SystemModstamp'),
'LastActivityDate': cds_record.get('LastActivityDate'),
'LastViewedDate': cds_record.get('LastViewedDate'),
'LastReferencedDate': cds_record.get('LastReferencedDate'),
'Number_of_Cows__c': cds_record.get('Number_of_Cows__c'),
'Number_of_Goats__c': cds_record.get('Number_of_Goats__c'),
'Been_living_in_the_same_location_for__c': cds_record.get('Been_living_in_the_same_location_for__c'),
'Next_of_Kin_Name__c': cds_record.get('Next_of_Kin_Name__c'),
'Next_of_Kin_Surname__c': cds_record.get('Next_of_Kin_Surname__c'),
'Number_of_Pigs__c': cds_record.get('Number_of_Pigs__c'),
'Share_name_phone_of_next_of_kin__c': cds_record.get('Share_name_phone_of_next_of_kin__c'),
'Next_of_Kin_Phone_Number__c': cds_record.get('Next_of_Kin_Phone_Number__c'),
'Number_of_Sheep__c': cds_record.get('Number_of_Sheep__c'),
'Sales_Manager__c': cds_record.get('Sales_Manager__c'),
'Lead_Name__c': cds_record.get('Lead_Name__c'),
'Account__c': cds_record.get('Account__c'),
'Own_the_land_for_product_installation__c': cds_record.get('Own_the_land_for_product_installation__c'),
'How_long_have_you_been_a_farmer__c': cds_record.get('How_long_have_you_been_a_farmer__c'),
'Do_you_have_animals__c': cds_record.get('Do_you_have_animals__c'),
'RM_No_Sales_Telesales_Dealer_Agent__c': cds_record.get('RM_No_Sales_Telesales_Dealer_Agent__c'),
'Type_of_fruits_and_vegetables_grown__c': cds_record.get('Type_of_fruits_and_vegetables_grown__c'),
'Pest_disease_control_pest_type_usage__c': cds_record.get('Pest_disease_control_pest_type_usage__c'),
'Other_machinery_and_equipment_ownership__c': cds_record.get('Other_machinery_and_equipment_ownership__c'),
'Salary_amount__c': cds_record.get('Salary_amount__c'),
'Main_purpose_of_acquiring_the_product__c': cds_record.get('Main_purpose_of_acquiring_the_product__c'),
'Primary_decision_maker_to_buy_product__c': cds_record.get('Primary_decision_maker_to_buy_product__c'),
'Main_source_of_income__c': cds_record.get('Main_source_of_income__c'),
'Periodicity_of_payment__c': cds_record.get('Periodicity_of_payment__c'),
'Compensation_for_the_help_provided__c': cds_record.get('Compensation_for_the_help_provided__c'),
'Duration_of_this_activity__c': cds_record.get('Duration_of_this_activity__c'),
'Total_amount_from_pension__c': cds_record.get('Total_amount_from_pension__c'),
'Total_amount_from_salary_government__c': cds_record.get('Total_amount_from_salary_government__c'),
'Credit_Check_Result__c': cds_record.get('Credit_Check_Result__c'),
'Other_sources_of_income_of_the_household__c': cds_record.get('Other_sources_of_income_of_the_household__c'),
'Credit_Score__c': cds_record.get('Credit_Score__c'),
'Rate_how_well_the_SA_was_able_to_educate__c': cds_record.get('Rate_how_well_the_SA_was_able_to_educate__c'),
'of_Kenyans_that_pay_suppliers_on_time__c': cds_record.get('of_Kenyans_that_pay_suppliers_on_time__c'),
'of_Kenyans_ever_defaulted_on_a_loan__c': cds_record.get('of_Kenyans_ever_defaulted_on_a_loan__c'),
'What_would_you_do_if_you_win_Ksh100_000__c': cds_record.get('What_would_you_do_if_you_win_Ksh100_000__c'),
'Overall_Risk_Assessment__c': cds_record.get('Overall_Risk_Assessment__c'),
'Relation_Manager__c': cds_record.get('Relation_Manager__c'),
'Types_of_crops_grown__c': cds_record.get('Types_of_crops_grown__c'),
'National_ID_Number_Lead__c': cds_record.get('National_ID_Number_Lead__c'),
'House_Members_F__c': cds_record.get('House_Members_F__c'),
'Gender_Lead__c': cds_record.get('Gender_Lead__c'),
'Mobile_Lead__c': cds_record.get('Mobile_Lead__c'),
'How_long_have_you_had_the_same_phone_No__c': cds_record.get('How_long_have_you_had_the_same_phone_No__c'),
'Email_Address_Lead__c': cds_record.get('Email_Address_Lead__c'),
'County_in_which_HouseHold_resides__c': cds_record.get('County_in_which_HouseHold_resides__c'),
'Living_in_the_same_location_for__c': cds_record.get('Living_in_the_same_location_for__c'),
'Relation_with_next_of_kin__c': cds_record.get('Relation_with_next_of_kin__c'),
'Number_of_Household_Members__c': cds_record.get('Number_of_Household_Members__c'),
'Product_Lead__c': cds_record.get('Product_Lead__c'),
'Ready_to_make_the_deposit_on__c': cds_record.get('Ready_to_make_the_deposit_on__c'),
'Amount_left_after_monthly_expenses__c': cds_record.get('Amount_left_after_monthly_expenses__c'),
'Type_of_crops_grown__c': cds_record.get('Type_of_crops_grown__c'),
'Crop_Grown__c': cds_record.get('Crop_Grown__c'),
'Wheat_sale__c': cds_record.get('Wheat_sale__c'),
'Maize_sale__c': cds_record.get('Maize_sale__c'),
'Paddy_sale__c': cds_record.get('Paddy_sale__c'),
'Irish_potatoes_sale__c': cds_record.get('Irish_potatoes_sale__c'),
'Cassava_sale__c': cds_record.get('Cassava_sale__c'),
'Beans_sale__c': cds_record.get('Beans_sale__c'),
'Sunflower_sale__c': cds_record.get('Sunflower_sale__c'),
'Groundnuts_sale__c': cds_record.get('Groundnuts_sale__c'),
'Other_stable_field_crops_sale__c': cds_record.get('Other_stable_field_crops_sale__c'),
'Wheat_self_consumption__c': cds_record.get('Wheat_self_consumption__c'),
'Maize_self_consumption__c': cds_record.get('Maize_self_consumption__c'),
'Paddy_self_consumption__c': cds_record.get('Paddy_self_consumption__c'),
'Irish_potatoes_self_consumption__c': cds_record.get('Irish_potatoes_self_consumption__c'),
'Cassava_self_consumption__c': cds_record.get('Cassava_self_consumption__c'),
'Beans_self_consumption__c': cds_record.get('Beans_self_consumption__c'),
'Sunflower_self_consumption__c': cds_record.get('Sunflower_self_consumption__c'),
'Groundnuts_self_consumption__c': cds_record.get('Groundnuts_self_consumption__c'),
'Other_staple_field_crop_self_consumption__c': cds_record.get('Other_staple_field_crop_self_consumption__c'),
'Tomatoes_sale__c': cds_record.get('Tomatoes_sale__c'),
'Cabbage_sale__c': cds_record.get('Cabbage_sale__c'),
'Spinach_sale__c': cds_record.get('Spinach_sale__c'),
'Onion_sale__c': cds_record.get('Onion_sale__c'),
'Green_beans_sale__c': cds_record.get('Green_beans_sale__c'),
'Other_fruits_and_vegetable_sale__c': cds_record.get('Other_fruits_and_vegetable_sale__c'),
'Tomatoes_self_consumption__c': cds_record.get('Tomatoes_self_consumption__c'),
'Cabbage_self_consumption__c': cds_record.get('Cabbage_self_consumption__c'),
'Spinach_self_consumption__c': cds_record.get('Spinach_self_consumption__c'),
'Onion_self_consumption__c': cds_record.get('Onion_self_consumption__c'),
'Green_Beans_self_consumption__c': cds_record.get('Green_Beans_self_consumption__c'),
'Other_fruit_vegetable_self_consumption__c': cds_record.get('Other_fruit_vegetable_self_consumption__c'),
'Harvest_Cycle_Per_Year__c': cds_record.get('Harvest_Cycle_Per_Year__c'),
'Same_number_as_provided_in_CDS1__c': cds_record.get('Same_number_as_provided_in_CDS1__c'),
'Recall_the_call__c': cds_record.get('Recall_the_call__c'),
'Farm_acreage__c': cds_record.get('Farm_acreage__c'),
'Main_Purpose_of_acquiring_the_pump__c': cds_record.get('Main_Purpose_of_acquiring_the_pump__c'),
'How_did_you_hear_about_SunCulture_pumps__c': cds_record.get('How_did_you_hear_about_SunCulture_pumps__c'),
'Other_sources_of_water__c': cds_record.get('Other_sources_of_water__c'),
'Hours_spent_fetching_water_every_week__c': cds_record.get('Hours_spent_fetching_water_every_week__c'),
'Amount_paid_for_getting_water_each_week__c': cds_record.get('Amount_paid_for_getting_water_each_week__c'),
'Amount_paid_for_water_other_pump_usage__c': cds_record.get('Amount_paid_for_water_other_pump_usage__c'),
'Customer_Data_Survey_Number__c': cds_record.get('Customer_Data_Survey_Number__c'),
'Quantity_of_water_usage_per_week__c': cds_record.get('Quantity_of_water_usage_per_week__c'),
'Water_tank_capacity__c': cds_record.get('Water_tank_capacity__c'),
'Electricity_connectivity__c': cds_record.get('Electricity_connectivity__c'),
'Number_of_financial_dependants__c': cds_record.get('Number_of_financial_dependants__c'),
'Number_of_working_age_adults_in_the_HH__c': cds_record.get('Number_of_working_age_adults_in_the_HH__c'),
'Number_of_pensioners_living_in_the_HH__c': cds_record.get('Number_of_pensioners_living_in_the_HH__c'),
'No_of_family_members_friends_helping__c': cds_record.get('No_of_family_members_friends_helping__c'),
'Number_of_businesses_before__c': cds_record.get('Number_of_businesses_before__c'),
'Average_monthly_income__c': cds_record.get('Average_monthly_income__c'),
'Understand_the_products_shared_with_you__c': cds_record.get('Understand_the_products_shared_with_you__c'),
'No_of_years_working_with_same_employer__c': cds_record.get('No_of_years_working_with_same_employer__c'),
'No_of_jobs_in_the_last_5yrs__c': cds_record.get('No_of_jobs_in_the_last_5yrs__c'),
'Total_amount_from_remittances__c': cds_record.get('Total_amount_from_remittances__c'),
'Total_amount_from_Agriculture__c': cds_record.get('Total_amount_from_Agriculture__c'),
'Total_amount_from_commerce_and_trade__c': cds_record.get('Total_amount_from_commerce_and_trade__c'),
'Total_Amt_from_salary_private_inst__c': cds_record.get('Total_Amt_from_salary_private_inst__c'),
'Total_amount_from_provision_of_services__c': cds_record.get('Total_amount_from_provision_of_services__c'),
'Agent_seek_to_understand_how_you_source__c': cds_record.get('Agent_seek_to_understand_how_you_source__c'),
'Amount_spent_on_school_fees__c': cds_record.get('Amount_spent_on_school_fees__c'),
'Amount_spent_on_food__c': cds_record.get('Amount_spent_on_food__c'),
'Amount_spent_on_farm_inputs__c': cds_record.get('Amount_spent_on_farm_inputs__c'),
'Amount_spent_on_rent__c': cds_record.get('Amount_spent_on_rent__c'),
'Amount_spent_on_loans__c': cds_record.get('Amount_spent_on_loans__c'),
'Amount_spent_on_other__c': cds_record.get('Amount_spent_on_other__c'),
'Currently_have_any_outstanding_loans__c': cds_record.get('Currently_have_any_outstanding_loans__c'),
'Total_amount_of_outstanding_loan_s__c': cds_record.get('Total_amount_of_outstanding_loan_s__c'),
'No_of_months_to_finish_paying_loan_s__c': cds_record.get('No_of_months_to_finish_paying_loan_s__c'),
'Preferred_banking_method__c': cds_record.get('Preferred_banking_method__c'),
'World_perception_supplier__c': cds_record.get('World_perception_supplier__c'),
'World_perception_default__c': cds_record.get('World_perception_default__c'),
'Number_of_loans_taken_in_the_last_2yrs__c': cds_record.get('Number_of_loans_taken_in_the_last_2yrs__c'),
'Periodicity_of_the_income__c': cds_record.get('Periodicity_of_the_income__c'),
'Like_further_clarification_on_our_Prod__c': cds_record.get('Like_further_clarification_on_our_Prod__c'),
'Likelihood_to_recommend_our_Prod__c': cds_record.get('Likelihood_to_recommend_our_Prod__c'),
'Name_Number_of_the_recommend_client__c': cds_record.get('Name_Number_of_the_recommend_client__c'),
'Agent__c': cds_record.get('Agent__c'),
'Survey_Completed__c': cds_record.get('Survey_Completed__c'),
'Duration_with_same_employer_5yrs_F__c': cds_record.get('Duration_with_same_employer_5yrs_F__c'),
'water_source_river__c': cds_record.get('water_source_river__c'),
'Stage__c': cds_record.get('Stage__c'),
'Account_Number__c': cds_record.get('Account_Number__c'),
'Gender_Male_F__c': cds_record.get('Gender_Male_F__c'),
'World_perception_supplier_6080_F__c': cds_record.get('World_perception_supplier_6080_F__c'),
'Overall_Risk_Assessment_Low_Risk_F__c': cds_record.get('Overall_Risk_Assessment_Low_Risk_F__c'),
'Other_sources_of_water_river_F__c': cds_record.get('Other_sources_of_water_river_F__c'),
'Other_sources_of_water_Borehole_F__c': cds_record.get('Other_sources_of_water_Borehole_F__c'),
'Do_you_have_animals_4F__c': cds_record.get('Do_you_have_animals_4F__c'),
'Do_you_have_animals_3F__c': cds_record.get('Do_you_have_animals_3F__c'),
'Types_of_crops_grown_1_type_F__c': cds_record.get('Types_of_crops_grown_1_type_F__c'),
'Type_of_fruits_and_vegetables_grown_4F__c': cds_record.get('Type_of_fruits_and_vegetables_grown_4F__c'),
'Type_of_fruits_and_vegetables_grown_0F__c': cds_record.get('Type_of_fruits_and_vegetables_grown_0F__c'),
'CDS1Tracker__c': cds_record.get('CDS1Tracker__c'),
'Birth_Date__c': cds_record.get('Birth_Date__c'),
'Date_of_Birth_46_55yrs_F__c': cds_record.get('Date_of_Birth_46_55yrs_F__c'),
'Date_of_Birth_older_than_55yrs_F__c': cds_record.get('Date_of_Birth_older_than_55yrs_F__c'),
'Hear_about_SunCulture_pumps_Online_F__c': cds_record.get('Hear_about_SunCulture_pumps_Online_F__c'),
'Hear_about_SunCulture_pumps_Radio_F__c': cds_record.get('Hear_about_SunCulture_pumps_Radio_F__c'),
'Other_Sources_of_HH_Income_Pension_F__c': cds_record.get('Other_Sources_of_HH_Income_Pension_F__c'),
'Date_of_Birth__c': cds_record.get('Date_of_Birth__c'),
'Email__c': cds_record.get('Email__c'),
'National_ID_Number__c': cds_record.get('National_ID_Number__c'),
'Gender__c': cds_record.get('Gender__c'),
'Mobile_Number__c': cds_record.get('Mobile_Number__c'),
'Working_age_adults_F__c': cds_record.get('Working_age_adults_F__c'),
'Harvest_Cycle_F__c': cds_record.get('Harvest_Cycle_F__c'),
'RM_Name__c': cds_record.get('RM_Name__c'),
'cds_source__c': cds_record.get('cds_source__c'),
'Did_you_previously_own_a_water_pump__c': cds_record.get('Did_you_previously_own_a_water_pump__c'),
'carbon_credit_which_pump_type__c': cds_record.get('carbon_credit_which_pump_type__c'),
'CDS1_Date__c': cds_record.get('CDS1_Date__c'),
'CDS2_Date__c': cds_record.get('CDS2_Date__c'),
'Number_of_Outstanding_Loans__c': cds_record.get('Number_of_Outstanding_Loans__c'),
'Depth_of_the_Water_Source__c': cds_record.get('Depth_of_the_Water_Source__c'),
'Total_Income__c': cds_record.get('Total_Income__c'),
'Total_Expenses__c': cds_record.get('Total_Expenses__c'),
'Remaining_Income_after_Expenses__c': cds_record.get('Remaining_Income_after_Expenses__c'),
'Lead_Record__c': cds_record.get('Lead_Record__c'),
'Creditscore__c': cds_record.get('Creditscore__c'),
'Clients_County_Ug__c': cds_record.get('Clients_County_Ug__c'),
'Clients_District__c': cds_record.get('Clients_District__c'),
'Clients_Nearest_Landmark__c': cds_record.get('Clients_Nearest_Landmark__c'),
'Clients_Parish__c': cds_record.get('Clients_Parish__c'),
'Clients_Sub_County__c': cds_record.get('Clients_Sub_County__c'),
'Clients_Village_ug__c': cds_record.get('Clients_Village_ug__c'),
'Amount_Spent_on_Treatment_Medical__c': cds_record.get('Amount_Spent_on_Treatment_Medical__c'),
'Reason_for_decline__c': cds_record.get('Reason_for_decline__c'),
'Seasonality_of_the_Water_Source__c': cds_record.get('Seasonality_of_the_Water_Source__c'),
'Product__c': cds_record.get('Product__c')
            }
             # Validate and truncate fields if necessary
            for field_name, value in cds_data.items():
                if isinstance(value, str):
                    # Check if the value exceeds the PostgreSQL column length
                    if len(value) > 18:  # Adjust the length limit as needed
                        #print(f"Warning: Field '{field_name}' exceeds length limit. Value: '{value}'")
                        cds_data[field_name] = value[:18]  # Truncate to 18 characters
            data.append(cds_data)
            
            # Attempt to insert CDS in batches
        execute_batch(cursor, query, data)
        db_connection.commit()
        print(f"Successfully upserted {len(cds_data)} cds")
    except Exception as e:
        db_connection.rollback()
        print(f"Error saving CDS record {cds_record.get('Id')}: {str(e)}")
        print("Traceback:", traceback.format_exc())
        
    finally:
        cursor.close()
        db_connection.close()
        
def main():
    """Main function to orchestrate the process."""
    # Track start time
    start_time = datetime.now()
    print(f"Script started at: {start_time}")
    
    # Get Salesforce token and fetch CDSS 
    access_token, instance_url = get_salesforce_token()

    if not access_token:
        print("Authentication failed. Exiting.")
        exit(1)
        
    print("\nFetching CDS from Salesforce...")
    cds = fetch_salesforce_cds_data(access_token, instance_url)
    
    if not cds:
        print("No CDS found or error occurred during fetch.")
        exit(2)
        
    print(f"Found {len(cds)} CDS to process")
    
    # Save CDS to PostgreSQL
    print("\nSaving CDS to PostgreSQL...")
    save_sf_cds_data_to_postgres(cds)
    print("Process completed successfully!")
    
    # Track end time and calculate duration
    end_time = datetime.now()
    duration = end_time - start_time
    print(f"Script ended at: {end_time}")
    print(f"Total duration: {duration}")

    # Check if the duration exceeds 15 minutes (AWS Lambda limit)
    if duration > timedelta(minutes=15):
        print("Warning: Script runtime exceeds 15 minutes!")
    else:
        print("Script completed within the 15-minute runtime limit.")

if __name__ == "__main__":
    main()