# Solution By Rodgers Nyangweso

In [23]:
#import needed modules
import pandas as pd
# Set the maximum number of displayed columns (e.g., display all columns)
pd.options.display.max_columns = None

import numpy as np

In [57]:
# Specify the column(s) and their desired data types
dtype_dict = {
    'hh_id': str
}
# load dataset
dataset1 = pd.read_csv("dataset1.csv", dtype=dtype_dict, low_memory=False)
print(f"dataset1 shape: {dataset1.shape}")
# view the first few rows
dataset1.head(3)

dataset1 shape: (2454, 322)


hh_name   hh_id     mobileuser                       bm_cycle country  \
0    Awoyo Rosa  173595  Acedo Goretty            FY18C1 Onaba Samuel  Uganda   
1  Asio Margate  173572  Acedo Goretty            FY18C1 Onaba Samuel  Uganda   
2  Okurut David  174305  Acedo Goretty  FY18C1 Mary Immaculate Akello  Uganda   

  project  office subcounty_or_sublocation village  household_members  \
0    Core  Soroti                  Akeriau  Adodoi                  3   
1    Core  Soroti                  Akeriau  Adodoi                  8   
2    Core  Soroti                  Akeriau  Akisim                  9   

  respondent_given_name_1 respondent_surname_1 given_name_household_member_1  \
0                    Rosa                Awoyo                       Richard   
1                 Magrate                 Asio                        Joseph   
2                   David               Okurut                         Joyce   

  given_name_household_member_2 given_name_household_member_3  \
0                    Joyce mary                           NaN   
1                           Ben                       Magrate   
2                     Elizabeth                       Jeffrey   

  given_name_household_member_4 given_name_household_member_5  \
0                           NaN                           NaN   
1                        Philip                         Betty   
2                      Emmanuel                        Thomas   

  given_name_household_member_6 given_name_household_member_7  \
0                           NaN                           NaN   
1                         Susan                           NaN   
2                          Paul                       Dominic   

  given_name_household_member_8 given_name_household_member_9  \
0                           NaN                           NaN   
1                           NaN                           NaN   
2                     Christine                           NaN   

  given_name_household_member_10 given_name_household_member_11  \
0                            NaN                            NaN   
1                            NaN                            NaN   
2                            NaN                            NaN   

  given_name_household_member_12 surname_household_member_1  \
0                            NaN                      Edong   
1                            NaN                    Elungat   
2                            NaN                     Asango   

  surname_household_member_2 surname_household_member_3  \
0                       Aduo                        NaN   
1                      Edonu                     Akiror   
2                      Aliba                      Ochen   

  surname_household_member_4 surname_household_member_5  \
0                        NaN                        NaN   
1                     Opolot                       Asio   
2                     Oumeno                      Egedo   

  surname_household_member_6 surname_household_member_7  \
0                        NaN                        NaN   
1                      Arayo                        NaN   
2                      Eselu                     Okurut   

  surname_household_member_8 surname_household_member_9  \
0                        NaN                        NaN   
1                        NaN                        NaN   
2                      Alimo                        NaN   

  surname_household_member_10 surname_household_member_11  \
0                         NaN                         NaN   
1                         NaN                         NaN   
2                         NaN                         NaN   

  surname_household_member_12  meals  sugar_intake  fish_meat_intake  \
0                         NaN      2             0                 0   
1                         NaN      1             0                 0   
2                         NaN      2             0                 1   

   legumes_intake cur

In [58]:
# descriptive statistics function
def descriptive_statistic(df):
    # Specifying datetime_is_numeric=True adopts the future behavior of Treating datetime data as categorical rather than numeric
    dataset1_descriptive_statistic_df = df.describe(include='all')
    return dataset1_descriptive_statistic_df
 

descriptive_statistic(dataset1)

hh_name   hh_id   mobileuser                  bm_cycle country  \
count           2454    2454         2454                      2454    2454   
unique          2406    2451           42                       210       2   
top     Opira Quinto  174179  Ann Osundwa  FY18C3 Akuguzibwe Joshua  Uganda   
freq               3       2          122                        45    1282   
mean             NaN     NaN          NaN                       NaN     NaN   
std              NaN     NaN          NaN                       NaN     NaN   
min              NaN     NaN          NaN                       NaN     NaN   
25%              NaN     NaN          NaN                       NaN     NaN   
50%              NaN     NaN          NaN                       NaN     NaN   
75%              NaN     NaN          NaN                       NaN     NaN   
max              NaN     NaN          NaN                       NaN     NaN   

       project  office subcounty_or_sublocation  village  household_members  \
count     2454    2454                     2454     2454        2454.000000   
unique       9       7                       84      206                NaN   
top       Core  Kitale              Kiryandongo  Kiswaza                NaN   
freq      1116     738                      206       31                NaN   
mean       NaN     NaN                      NaN      NaN           6.581092   
std        NaN     NaN                      NaN      NaN           3.120449   
min        NaN     NaN                      NaN      NaN           0.000000   
25%        NaN     NaN                      NaN      NaN           5.000000   
50%        NaN     NaN                      NaN      NaN           6.000000   
75%        NaN     NaN                      NaN      NaN           8.000000   
max        NaN     NaN                      NaN      NaN          71.000000   

       respondent_given_name_1 respondent_surname_1  \
count                     2451                 2451   
unique                    1357                 1568   
top                  Christine               Akello   
freq                        38                   39   
mean                       NaN                  NaN   
std                        NaN                  NaN   
min                        NaN                  NaN   
25%                        NaN                  NaN   
50%                        NaN                  NaN   
75%                        NaN                  NaN   
max                        NaN                  NaN   

       given_name_household_member_1 given_name_household_member_2  \
count                           2431                          2300   
unique                          1220                          1103   
top                             John                         Brian   
freq                              45                            32   
mean                             NaN                           NaN   
std                              NaN                           NaN   
min                              NaN                           NaN   
25%                              NaN                           NaN   
50%                              NaN                           NaN   
75%                              NaN                           NaN   
max                              NaN                           NaN   

       given_name_household_member_3 given_name_household_member_4  \
count                           2142                          1894   
unique                          1063                          1008   
top                            Brian                      Emmanuel   
freq                              26                            27   
mean                             NaN                           NaN   
std                              NaN                           NaN   
min                              NaN                           NaN   
25%                              NaN                 

# Question 1

## Question 1. (a): How many observations and variables are in the dataset?

In [59]:
# Get the shape of the dataset
num_observations, num_variables = dataset1.shape

print(f"Number of observations in dataset1: {num_observations}")
print(f"Number of variables in dataset1: {num_variables}")

Number of observations in dataset1: 2454
Number of variables in dataset1: 322


## Question 1. (b): What is the unit of observation?
Unit of observation is the __household week__ since data is collected weekly, and each row represents the consumption, expenditure, and savings for a particular household during a specific week.

Explanation
1.  Each row pertains to a particular household, indicating that the data is collected at the household level.
2.  The data is collected on a weekly basis, so each row represents one week's worth of data for the household.

## Question 1.(c): Data contains some duplicates in terms of household ID (`hh_id`). How many duplicates are there in this data set?

In [60]:
# Identify duplicate hh_id values
duplicate_hh_ids = dataset1[dataset1.duplicated(subset='hh_id', keep=False)]['hh_id'].unique()

# Count the number of unique hh_id values that have duplicates
num_duplicate_hh_ids = len(duplicate_hh_ids)

print(f"Number of unique household IDs (hh_id) that have duplicates: {num_duplicate_hh_ids}")


Number of unique household IDs (hh_id) that have duplicates: 3


Explanation
- Use `duplicated` method in pandas to identify duplicate `hh_ids`.
  - `dataset1[dataset1.duplicated(subset='hh_id', keep=False)]['hh_id'].unique()` extracts the unique `hh_id` values that appear more than once in the dataset.
  - The `keep=False` argument ensures that all occurrences of the duplicated hh_ids are marked as duplicates, not just the subsequent ones.
- Then, count the number of duplicate entries.
  - `len(duplicate_hh_ids)` gives the count of unique `hh_id` values that have duplicates.

## Question1.(d): List country `hh_id` and respondent given name 1 (`given_name_household_member_1`) for all duplicate observations

In [61]:
# Identify duplicates based on hh_id
duplicates = dataset1[dataset1.duplicated(subset='hh_id', keep=False)]

# Select the relevant columns: country, hh_id, and given_name_household_member_1
duplicates_info = duplicates[['country', 'hh_id', 'given_name_household_member_1']]

# Display the duplicate observations
duplicates_info

country   hh_id given_name_household_member_1
2201  Uganda  174179                        Sharon
2235  Uganda  174179                          Alex
2387  Uganda  178903                        Nighty
2424  Uganda  187589                         Fiona
2432  Uganda  178903                          Mary
2450  Uganda  187589                        Prossy

Explanation
- `dataset1.duplicated(subset='hh_id', keep=False)` function identifies all rows that are duplicates based on the `hh_id` column. The `keep=False` argument ensures that all occurrences of the duplicated `hh_ids` are included.
- `duplicates[['country', 'hh_id', 'given_name_household_member_1']]` extracts the columns `country`, `hh_id`, and `given_name_household_member_1` from the DataFrame containing the duplicate entries.

## Question 1.(e): Drop excess observations as follows:
- Where `hh_id` is 174179, drop the observation that has the respondent as Scovia
- Where `hh_id` is 178903, drop the observation that has the respondent as David
- Where `hh_id` is 187589, drop the observation that has the respondent as Immaculate


In [63]:
def drop_specific_observations(df):
    print("Original dataframe shape:", dataset1.shape)

    # Define the conditions for dropping observations
    condition = (
        ((df['hh_id'] == 174179) & (df['respondent_given_name_1'] == 'Scovia')) |
        ((df['hh_id'] == 178903) & (df['respondent_given_name_1'] == 'David')) |
        ((df['hh_id'] == 187589) & (df['respondent_given_name_1'] == 'Immaculate'))
    )

    # Apply the condition to filter the DataFrame
    df_without_excess_obersavations = df[~condition]

    print("Dataframe without excess obersavations, shape:", df_without_excess_obersavations.shape)

    return df_without_excess_obersavations

# Example usage
dataset1_without_excess_obersavations = drop_specific_observations(dataset1.copy())

Original dataframe shape: (2454, 322)
Dataframe without excess obersavations, shape: (2454, 322)


Explanation
- This function defines a single condition that combines all the specified conditions using the `|` operator. The DataFrame is then filtered using this combined condition. The `~` operator is used to invert the condition so that rows matching the condition are dropped.

## Question 1.(f): What is the proportion of households from `Uganda`?

In [64]:
def get_uganda_household_proportion(df):
    # Filter the dataset for households in Uganda
    uganda_households = df[df['country'] == 'Uganda']

    # Calculate the number of unique household IDs in Uganda
    unique_uganda_households = uganda_households['hh_id'].nunique()

    # Calculate the total number of unique household IDs in the dataset
    total_households = df['hh_id'].nunique()

    # Calculate the proportion of households in Uganda
    proportion = unique_uganda_households / total_households
    
    return proportion

proportion = get_uganda_household_proportion(dataset1_without_excess_obersavations)
print(f"Proportion of households in Uganda: {proportion:.2%}")

Proportion of households in Uganda: 52.18%


Explanation
- The function
  - Filters the `updated_dataset1` DataFrame for rows where the country column is "`Uganda`".
  - Calculates the number of unique household IDs (`hh_id`) in Uganda.
  - Calculates the total number of unique household IDs in the entire dataset.
  - Computes the proportion of households in Uganda by dividing the number of unique Ugandan households by the total number of unique households.

# Question 2

## Question 2(a): Rename variables

In [65]:
# Define the dictionary for renaming columns
new_names = {
    'how_much_does_a_unit_of_sweet_po': 'ucost_sweetpotatoes',
    'quantity_other_food  ': 'quantity_otherfood',
    'ucode_other_food': 'ucode_otherfood',
    'consumption_avocado' : 'consumption_avocados',
    'consumption_otherfruitveg_descri' : 'specify_otherfruitveg_descri'
}

def rename_columns_and_save(df, new_names):
    # Rename the columns based on the new_names dictionary
    Dataset1_clean = df.rename(columns=new_names)
    
    return Dataset1_clean

Dataset1_clean = rename_columns_and_save(dataset1_without_excess_obersavations, new_names)

# Save the cleaned dataset
Dataset1_clean.to_csv('Dataset1_clean.csv', index=False)

# Display the first few rows of the cleaned DataFrame
Dataset1_clean.head(3)

hh_name   hh_id     mobileuser                       bm_cycle country  \
0    Awoyo Rosa  173595  Acedo Goretty            FY18C1 Onaba Samuel  Uganda   
1  Asio Margate  173572  Acedo Goretty            FY18C1 Onaba Samuel  Uganda   
2  Okurut David  174305  Acedo Goretty  FY18C1 Mary Immaculate Akello  Uganda   

  project  office subcounty_or_sublocation village  household_members  \
0    Core  Soroti                  Akeriau  Adodoi                  3   
1    Core  Soroti                  Akeriau  Adodoi                  8   
2    Core  Soroti                  Akeriau  Akisim                  9   

  respondent_given_name_1 respondent_surname_1 given_name_household_member_1  \
0                    Rosa                Awoyo                       Richard   
1                 Magrate                 Asio                        Joseph   
2                   David               Okurut                         Joyce   

  given_name_household_member_2 given_name_household_member_3  \
0                    Joyce mary                           NaN   
1                           Ben                       Magrate   
2                     Elizabeth                       Jeffrey   

  given_name_household_member_4 given_name_household_member_5  \
0                           NaN                           NaN   
1                        Philip                         Betty   
2                      Emmanuel                        Thomas   

  given_name_household_member_6 given_name_household_member_7  \
0                           NaN                           NaN   
1                         Susan                           NaN   
2                          Paul                       Dominic   

  given_name_household_member_8 given_name_household_member_9  \
0                           NaN                           NaN   
1                           NaN                           NaN   
2                     Christine                           NaN   

  given_name_household_member_10 given_name_household_member_11  \
0                            NaN                            NaN   
1                            NaN                            NaN   
2                            NaN                            NaN   

  given_name_household_member_12 surname_household_member_1  \
0                            NaN                      Edong   
1                            NaN                    Elungat   
2                            NaN                     Asango   

  surname_household_member_2 surname_household_member_3  \
0                       Aduo                        NaN   
1                      Edonu                     Akiror   
2                      Aliba                      Ochen   

  surname_household_member_4 surname_household_member_5  \
0                        NaN                        NaN   
1                     Opolot                       Asio   
2                     Oumeno                      Egedo   

  surname_household_member_6 surname_household_member_7  \
0                        NaN                        NaN   
1                      Arayo                        NaN   
2                      Eselu                     Okurut   

  surname_household_member_8 surname_household_member_9  \
0                        NaN                        NaN   
1                        NaN                        NaN   
2                      Alimo                        NaN   

  surname_household_member_10 surname_household_member_11  \
0                         NaN                         NaN   
1                         NaN                         NaN   
2                         NaN                         NaN   

  surname_household_member_12  meals  sugar_intake  fish_meat_intake  \
0                         NaN      2             0                 0   
1                         NaN      1             0                 0   
2                         NaN      2             0                 1   

   legumes_intake cur

Explantion
- This function now takes `updated_dataset1` as input and renames its columns according to the `new_names` dictionary, returning the cleaned DataFrame as `Dataset1_clean`.

### Test: Question 2(a)

In [67]:
# Define a list of hh_ids to filter for
hh_id_test_list = ["173595", "173572"]
hh_id_test_list = Dataset1_clean[ (Dataset1_clean['hh_id'] == hh_id_test_list[0]) | (Dataset1_clean['hh_id'] == hh_id_test_list[1]) ]
hh_id_test_list

hh_name   hh_id     mobileuser             bm_cycle country project  \
0    Awoyo Rosa  173595  Acedo Goretty  FY18C1 Onaba Samuel  Uganda    Core   
1  Asio Margate  173572  Acedo Goretty  FY18C1 Onaba Samuel  Uganda    Core   

   office subcounty_or_sublocation village  household_members  \
0  Soroti                  Akeriau  Adodoi                  3   
1  Soroti                  Akeriau  Adodoi                  8   

  respondent_given_name_1 respondent_surname_1 given_name_household_member_1  \
0                    Rosa                Awoyo                       Richard   
1                 Magrate                 Asio                        Joseph   

  given_name_household_member_2 given_name_household_member_3  \
0                    Joyce mary                           NaN   
1                           Ben                       Magrate   

  given_name_household_member_4 given_name_household_member_5  \
0                           NaN                           NaN   
1                        Philip                         Betty   

  given_name_household_member_6 given_name_household_member_7  \
0                           NaN                           NaN   
1                         Susan                           NaN   

  given_name_household_member_8 given_name_household_member_9  \
0                           NaN                           NaN   
1                           NaN                           NaN   

  given_name_household_member_10 given_name_household_member_11  \
0                            NaN                            NaN   
1                            NaN                            NaN   

  given_name_household_member_12 surname_household_member_1  \
0                            NaN                      Edong   
1                            NaN                    Elungat   

  surname_household_member_2 surname_household_member_3  \
0                       Aduo                        NaN   
1                      Edonu                     Akiror   

  surname_household_member_4 surname_household_member_5  \
0                        NaN                        NaN   
1                     Opolot                       Asio   

  surname_household_member_6 surname_household_member_7  \
0                        NaN                        NaN   
1                      Arayo                        NaN   

  surname_household_member_8 surname_household_member_9  \
0                        NaN                        NaN   
1                        NaN                        NaN   

  surname_household_member_10 surname_household_member_11  \
0                         NaN                         NaN   
1                         NaN                         NaN   

  surname_household_member_12  meals  sugar_intake  fish_meat_intake  \
0                         NaN      2             0                 0   
1                         NaN      1             0                 0   

   legumes_intake currently_save  saved_amount difficult_situation  \
0               7            Yes       50000.0                 Yes   
1               7            Yes       40000.0                  No   

  explain_difficult_situation difficult_situatio_support  \
0                    Sickness                        Yes   
1                         NaN                        NaN   

  difficult_situation_recover future_shocks future_shocks_advances  \
0    Yes, partially recovered           Yes                    Yes   
1                         NaN           Yes                    Yes   

            advance_details richer_or_poorer members_away  \
0    Has a goat and cassava           Poorer           No   
1  Livestock and food crops           Richer           No   

   household_members_away consumption_rice  quantity_rice ucode_rice  \
0                     NaN               No            NaN        NaN   
1                     NaN              Yes            8.0   Kilogram   

   ucost_rice consumption_maizeflour  qu

## Question 2(b):
- This data is wide by `hh_id`. Reshape the data to a long format for all `consumption_` `quantity_` `ucode_` `ucost_`. Save the new variable created as `“Product”` 

In [71]:
# Function to reshape the DataFrame from wide to long format
def identify_columns_to_melt(df):
    # Identify columns to melt
    melt_columns = [col for col in df.columns if col.startswith(('consumption_', 'quantity_', 'ucode_', 'ucost_'))]

    # Count the number of records in the list
    num_records = len(melt_columns)

    # Print the number of records
    print(f"The number of columns is: {num_records}")
    return melt_columns

print(identify_columns_to_melt(Dataset1_clean))

The number of columns is: 143
['consumption_rice', 'quantity_rice', 'ucode_rice', 'ucost_rice', 'consumption_maizeflour', 'quantity_maizeflour', 'ucode_maizeflour', 'ucost_maizeflour', 'consumption_maizecobs', 'quantity_maizecobs', 'ucode_maizecobs', 'ucost_maizecobs', 'consumption_millet', 'quantity_millet', 'ucode_millet', 'ucost_millet', 'consumption_sorghum', 'quantity_sorghum', 'ucode_sorghum', 'ucost_sorghum', 'consumption_matooke', 'quantity_matooke', 'ucode_matooke', 'ucost_matooke', 'consumption_irishpotatoes', 'quantity_irishpotatoes', 'ucode_irishpotatoes', 'ucost_irishpotatoes', 'consumption_sweetpotatoes', 'quantity_sweetpotatoes', 'ucode_sweetpotatoes', 'ucost_sweetpotatoes', 'consumption_cassava', 'quantity_cassava', 'ucode_cassava', 'ucost_cassava', 'consumption_yams', 'quantity_yams', 'ucode_yams', 'ucost_yams', 'consumption_pumpkin', 'quantity_pumpkin', 'ucode_pumpkin', 'ucost_pumpkin', 'consumption_carrots', 'quantity_carrots', 'ucode_carrots', 'ucost_carrots', 'cons

In [72]:
# Function to reshape the DataFrame from wide to long format
def reshape_data_wide_to_long(df):
    # Step 1: Melt the consumption columns
    consumption_columns = [col for col in df.columns if col.startswith('consumption_')]
    consumption_long = pd.melt(
        df,
        id_vars=['hh_id', 'country'],
        value_vars=consumption_columns,
        var_name='Product',
        value_name='consumption'
    )
    # Remove the 'consumption_' prefix from the 'Product' column
    consumption_long['Product'] = consumption_long['Product'].str.replace('consumption_', '')

    # Step 2: Melt the quantity columns
    quantity_columns = [col for col in df.columns if col.startswith('quantity_')]
    quantity_long = pd.melt(
        df,
        id_vars=['hh_id', 'country'],
        value_vars=quantity_columns,
        var_name='Product',
        value_name='quantity'
    )
    # Remove the 'quantity_' prefix from the 'Product' column
    quantity_long['Product'] = quantity_long['Product'].str.replace('quantity_', '')

    # Step 3: Melt the ucost columns
    ucost_columns = [col for col in df.columns if col.startswith('ucost_')]
    ucost_long = pd.melt(
        df,
        id_vars=['hh_id', 'country'],
        value_vars=ucost_columns,
        var_name='Product',
        value_name='ucost'
    )
    # Remove the 'ucost_' prefix from the 'Product' column
    ucost_long['Product'] = ucost_long['Product'].str.replace('ucost_', '')

    # Step 4: Melt the ucode columns
    ucode_columns = [col for col in df.columns if col.startswith('ucode_')]
    ucode_long = pd.melt(
        df,
        id_vars=['hh_id', 'country'],
        value_vars=ucode_columns,
        var_name='Product',
        value_name='ucode'
    )
    # Remove the 'ucode_' prefix from the 'Product' column
    ucode_long['Product'] = ucode_long['Product'].str.replace('ucode_', '')

    # Step 5: Merge all long DataFrames on 'hh_id' and 'Product'
    Dataset1_clean_in_long_format = pd.merge(consumption_long, quantity_long, on=['hh_id','country', 'Product'], how='left')
    Dataset1_clean_in_long_format = pd.merge(Dataset1_clean_in_long_format, ucost_long, on=['hh_id','country', 'Product'], how='left')
    Dataset1_clean_in_long_format = pd.merge(Dataset1_clean_in_long_format, ucode_long, on=['hh_id', 'country', 'Product'], how='left')
    
    # Check the number of observations (rows) and variables (columns)
    num_observations = Dataset1_clean_in_long_format.shape[0]
    num_variables = Dataset1_clean_in_long_format.shape[1]

    print(f"Number of observations (rows): {num_observations}")
    print(f"Number of variables (columns): {num_variables}")
    return Dataset1_clean_in_long_format

Dataset1_clean_in_long_format = reshape_data_wide_to_long(Dataset1_clean)

# save the result to a dataframe
Dataset1_clean_in_long_format.to_csv("Dataset1_clean_in_long_format.csv", index=False)

# preview the result
Dataset1_clean_in_long_format.head()

Number of observations (rows): 89808
Number of variables (columns): 7


hh_id country Product consumption  quantity   ucost     ucode
0  173595  Uganda    rice          No       NaN     NaN       NaN
1  173572  Uganda    rice         Yes       8.0  5000.0  Kilogram
2  174305  Uganda    rice          No       NaN     NaN       NaN
3  174401  Uganda    rice          No       NaN     NaN       NaN
4  175138  Uganda    rice         Yes       2.0  5000.0  Kilogram

### Explanation: Question 2(b)
- Identify columns starting with `consumption_` and melt them, then remove the prefix from the Product column.
- Identify columns starting with `quantity_` and melt them, then remove the prefix from the Product column.
-  Identify columns starting with `ucost_` and melt them, then remove the prefix from the Product column.
-  Identify columns starting with `ucode_` and melt them, then remove the prefix from the Product column.
-  Merge all the long DataFrames on `hh_id` and Product using left joins.

### Test: Question 2(b)

In [73]:
# Define a list of hh_ids to filter for
test_hh_id_list = ["173595"]
test_hh_id_list_df = Dataset1_clean_in_long_format[ (Dataset1_clean_in_long_format['hh_id'] == test_hh_id_list[0])]
print(test_hh_id_list_df.shape)
test_hh_id_list_df

(36, 7)


hh_id country        Product consumption  quantity    ucost   ucode
0      173595  Uganda           rice          No       NaN      NaN     NaN
2496   173595  Uganda     maizeflour          No       NaN      NaN     NaN
4992   173595  Uganda      maizecobs          No       NaN      NaN     NaN
7488   173595  Uganda         millet          No       NaN      NaN     NaN
9984   173595  Uganda        sorghum          No       NaN      NaN     NaN
12480  173595  Uganda        matooke          No       NaN      NaN     NaN
14976  173595  Uganda  irishpotatoes          No       NaN      NaN     NaN
17472  173595  Uganda  sweetpotatoes         Yes       3.0     99.0   Basin
19968  173595  Uganda        cassava         Yes       1.0  25000.0   Basin
22464  173595  Uganda           yams          No       NaN      NaN     NaN
24960  173595  Uganda        pumpkin          No       NaN      NaN     NaN
27456  173595  Uganda        carrots          No       NaN      NaN     NaN
29952  173595  Uganda        cabbage          No       NaN      NaN     NaN
32448  173595  Uganda    localgreens         Yes       4.0    500.0    Heap
34944  173595  Uganda       tomatoes         Yes       2.0    500.0    Heap
37440  173595  Uganda         onions         Yes       1.0    500.0    Heap
39936  173595  Uganda        mangoes          No       NaN      NaN     NaN
42432  173595  Uganda         pawpaw          No       NaN      NaN     NaN
44928  173595  Uganda      jackfruit          No       NaN      NaN     NaN
47400  173595  Uganda       avocados          No       NaN      NaN     NaN
49896  173595  Uganda   sweetbananas          No       NaN      NaN     NaN
52392  173595  Uganda  otherfruitveg          No       NaN      NaN     NaN
54888  173595  Uganda     organmeats          No       NaN      NaN     NaN
57384  173595  Uganda           meat          No       NaN      NaN     NaN
59880  173595  Uganda           fish          No       NaN      NaN     NaN
62376  173595  Uganda           eggs          No       NaN      NaN     NaN
64872  173595  Uganda          dairy          No       NaN      NaN     NaN
67368  173595  Uganda           nuts          No       NaN      NaN     NaN
69864  173595  Uganda        legumes         Yes       8.0   2000.0     Cup
72360  173595  Uganda     cookingoil         Yes       2.0    500.0  Sacket
74856  173595  Uganda          sugar          No       NaN      NaN     NaN
77352  173595  Uganda           salt         Yes       1.0    600.0  Sacket
79848  173595  Uganda          royco          No       NaN      NaN     NaN
82344  173595  Uganda            tea          No       NaN      NaN     NaN
84840  173595  Uganda        alcohol         Yes       2.0   1000.0     Cup
87336  173595  Uganda      otherfood          No       NaN      NaN     NaN

# Question 3

## Question 3(a): Replace both `quantity` and `ucost` to `zero`, where there was not `consumption` (`consumption=No`)

In [74]:
def replace_zero_where_no_consumption(df):
    """
    Replace quantity and ucost with zero where consumption is 'No'.
    
    Parameters:
    df (pd.DataFrame): The input DataFrame with columns ['hh_id', 'Product', 'consumption', 'quantity', 'ucost', 'ucode'].
    
    Returns:
    pd.DataFrame: The modified DataFrame with quantity and ucost set to zero where consumption is 'NO'.
    """
    df_copy = df.copy()
    condition = df_copy['consumption'] == 'No'
    
    # Replace quantity and ucost with zero where consumption is 'NO'
    df_copy.loc[condition, 'quantity'] = df_copy.loc[condition, 'quantity'].fillna(0)
    df_copy.loc[condition, 'ucost'] = df_copy.loc[condition, 'ucost'].fillna(0)

    print("Resultant dataframe shape:", df_copy.shape)

    return df_copy

# Apply the function to Dataset1_clean_long_format
Dataset1_clean_in_long_format_modified = replace_zero_where_no_consumption(Dataset1_clean_in_long_format)

# Save the result to a CSV file
# Dataset1_clean_in_long_format_modified.to_csv("Dataset1_clean_long_format_modified.csv", index=False)

# preview the result
Dataset1_clean_in_long_format_modified.head()

Resultant dataframe shape: (89808, 7)


hh_id country Product consumption  quantity   ucost     ucode
0  173595  Uganda    rice          No       0.0     0.0       NaN
1  173572  Uganda    rice         Yes       8.0  5000.0  Kilogram
2  174305  Uganda    rice          No       0.0     0.0       NaN
3  174401  Uganda    rice          No       0.0     0.0       NaN
4  175138  Uganda    rice         Yes       2.0  5000.0  Kilogram

### Explanation 3(a)
- Define `replace_zero_where_no_consumption(df)` takes a DataFrame `df` as input and creates a copy of the input DataFrame to avoid modifying the original DataFrame.
- It identifies rows where consumption is "`No`"
- For these rows, it fills `None` (or `NaN`) values in `quantity` and `ucost` columns with `0`.

### Test: Question 3(a)

In [75]:
# Define a list of hh_ids to filter for
test_hh_id_list = ["173595"]
test_hh_id_list_df = Dataset1_clean_in_long_format_modified[ (Dataset1_clean_in_long_format_modified['hh_id'] == test_hh_id_list[0])]
print(test_hh_id_list_df.shape)
test_hh_id_list_df

(36, 7)


hh_id country        Product consumption  quantity    ucost   ucode
0      173595  Uganda           rice          No       0.0      0.0     NaN
2496   173595  Uganda     maizeflour          No       0.0      0.0     NaN
4992   173595  Uganda      maizecobs          No       0.0      0.0     NaN
7488   173595  Uganda         millet          No       0.0      0.0     NaN
9984   173595  Uganda        sorghum          No       0.0      0.0     NaN
12480  173595  Uganda        matooke          No       0.0      0.0     NaN
14976  173595  Uganda  irishpotatoes          No       0.0      0.0     NaN
17472  173595  Uganda  sweetpotatoes         Yes       3.0     99.0   Basin
19968  173595  Uganda        cassava         Yes       1.0  25000.0   Basin
22464  173595  Uganda           yams          No       0.0      0.0     NaN
24960  173595  Uganda        pumpkin          No       0.0      0.0     NaN
27456  173595  Uganda        carrots          No       0.0      0.0     NaN
29952  173595  Uganda        cabbage          No       0.0      0.0     NaN
32448  173595  Uganda    localgreens         Yes       4.0    500.0    Heap
34944  173595  Uganda       tomatoes         Yes       2.0    500.0    Heap
37440  173595  Uganda         onions         Yes       1.0    500.0    Heap
39936  173595  Uganda        mangoes          No       0.0      0.0     NaN
42432  173595  Uganda         pawpaw          No       0.0      0.0     NaN
44928  173595  Uganda      jackfruit          No       0.0      0.0     NaN
47400  173595  Uganda       avocados          No       0.0      0.0     NaN
49896  173595  Uganda   sweetbananas          No       0.0      0.0     NaN
52392  173595  Uganda  otherfruitveg          No       0.0      0.0     NaN
54888  173595  Uganda     organmeats          No       0.0      0.0     NaN
57384  173595  Uganda           meat          No       0.0      0.0     NaN
59880  173595  Uganda           fish          No       0.0      0.0     NaN
62376  173595  Uganda           eggs          No       0.0      0.0     NaN
64872  173595  Uganda          dairy          No       0.0      0.0     NaN
67368  173595  Uganda           nuts          No       0.0      0.0     NaN
69864  173595  Uganda        legumes         Yes       8.0   2000.0     Cup
72360  173595  Uganda     cookingoil         Yes       2.0    500.0  Sacket
74856  173595  Uganda          sugar          No       0.0      0.0     NaN
77352  173595  Uganda           salt         Yes       1.0    600.0  Sacket
79848  173595  Uganda          royco          No       0.0      0.0     NaN
82344  173595  Uganda            tea          No       0.0      0.0     NaN
84840  173595  Uganda        alcohol         Yes       2.0   1000.0     Cup
87336  173595  Uganda      otherfood          No       0.0      0.0     NaN

## Question 3(b): Replace both `quantity` and `ucost` to `missing` where the `quantity` captured is either equal to `99`, `98` or `999`

In [76]:
def replace_with_missing_for_specific_quantities(df):
    """
    Replace quantity and ucost with 'missing' where quantity is either 99, 98, or 999.
    
    Parameters:
    df (pd.DataFrame): The input DataFrame with columns ['hh_id', 'Product', 'consumption', 'quantity', 'ucost', 'ucode'].
    
    Returns:
    pd.DataFrame: The modified DataFrame with quantity and ucost set to 'missing' where quantity is either 99, 98, or 999.
    """
    df_copy = df.copy()

    # Convert quantity and ucost columns to float type to handle NaN values
    df_copy['quantity'] = df_copy['quantity'].astype(float)
    df_copy['ucost'] = df_copy['ucost'].astype(float)
    
    # Condition to identify rows where quantity is 99, 98, or 999 or ucost is 99, 98, or 999
    quantity_condition = df_copy['quantity'].isin([99, 98, 999])
    ucost_condition = df_copy['ucost'].isin([99, 98, 999])
    
    # Replace quantity and ucost with NaN where the condition is met
    df_copy.loc[quantity_condition, ['quantity', 'ucost']] = np.nan
    df_copy.loc[ucost_condition, ['quantity', 'ucost']] = np.nan
    
    return df_copy

# Apply the function to Dataset1_clean_long_format
Dataset1_clean_in_long_format_modified = replace_with_missing_for_specific_quantities(Dataset1_clean_in_long_format_modified)

# Save the result to a CSV file
# Dataset1_clean_in_long_format_modified.to_csv("Dataset1_clean_in_long_format_modified.csv", index=False)

# Preview the result
Dataset1_clean_in_long_format_modified.head()

hh_id country Product consumption  quantity   ucost     ucode
0  173595  Uganda    rice          No       0.0     0.0       NaN
1  173572  Uganda    rice         Yes       8.0  5000.0  Kilogram
2  174305  Uganda    rice          No       0.0     0.0       NaN
3  174401  Uganda    rice          No       0.0     0.0       NaN
4  175138  Uganda    rice         Yes       2.0  5000.0  Kilogram

### Explanation 3(b)
- This function first creates a copy of the input DataFrame and then converts the `quantity` and `ucost` columns to `float` to handle `NaN` values. It then creates two conditions: one for `quantity` and one for `ucost`, checking if either column contains the values `[99, 98, 999]`. The code then replaces `quantity` and `ucost` with `NaN` wherever these conditions are met.

### Test 3(b)

In [77]:
# Define a list of hh_ids to filter for
test_hh_id_list = ["173595"]
test_hh_id_list_df = Dataset1_clean_in_long_format_modified[ (Dataset1_clean_in_long_format_modified['hh_id'] == test_hh_id_list[0])]
print(test_hh_id_list_df.shape)
test_hh_id_list_df

(36, 7)


hh_id country        Product consumption  quantity    ucost   ucode
0      173595  Uganda           rice          No       0.0      0.0     NaN
2496   173595  Uganda     maizeflour          No       0.0      0.0     NaN
4992   173595  Uganda      maizecobs          No       0.0      0.0     NaN
7488   173595  Uganda         millet          No       0.0      0.0     NaN
9984   173595  Uganda        sorghum          No       0.0      0.0     NaN
12480  173595  Uganda        matooke          No       0.0      0.0     NaN
14976  173595  Uganda  irishpotatoes          No       0.0      0.0     NaN
17472  173595  Uganda  sweetpotatoes         Yes       NaN      NaN   Basin
19968  173595  Uganda        cassava         Yes       1.0  25000.0   Basin
22464  173595  Uganda           yams          No       0.0      0.0     NaN
24960  173595  Uganda        pumpkin          No       0.0      0.0     NaN
27456  173595  Uganda        carrots          No       0.0      0.0     NaN
29952  173595  Uganda        cabbage          No       0.0      0.0     NaN
32448  173595  Uganda    localgreens         Yes       4.0    500.0    Heap
34944  173595  Uganda       tomatoes         Yes       2.0    500.0    Heap
37440  173595  Uganda         onions         Yes       1.0    500.0    Heap
39936  173595  Uganda        mangoes          No       0.0      0.0     NaN
42432  173595  Uganda         pawpaw          No       0.0      0.0     NaN
44928  173595  Uganda      jackfruit          No       0.0      0.0     NaN
47400  173595  Uganda       avocados          No       0.0      0.0     NaN
49896  173595  Uganda   sweetbananas          No       0.0      0.0     NaN
52392  173595  Uganda  otherfruitveg          No       0.0      0.0     NaN
54888  173595  Uganda     organmeats          No       0.0      0.0     NaN
57384  173595  Uganda           meat          No       0.0      0.0     NaN
59880  173595  Uganda           fish          No       0.0      0.0     NaN
62376  173595  Uganda           eggs          No       0.0      0.0     NaN
64872  173595  Uganda          dairy          No       0.0      0.0     NaN
67368  173595  Uganda           nuts          No       0.0      0.0     NaN
69864  173595  Uganda        legumes         Yes       8.0   2000.0     Cup
72360  173595  Uganda     cookingoil         Yes       2.0    500.0  Sacket
74856  173595  Uganda          sugar          No       0.0      0.0     NaN
77352  173595  Uganda           salt         Yes       1.0    600.0  Sacket
79848  173595  Uganda          royco          No       0.0      0.0     NaN
82344  173595  Uganda            tea          No       0.0      0.0     NaN
84840  173595  Uganda        alcohol         Yes       2.0   1000.0     Cup
87336  173595  Uganda      otherfood          No       0.0      0.0     NaN

## Question 3(c) and 3(d): 
- For all values of `ucost` less than `100` shillings in `Uganda`, replace them to `missing`
- For all values of `ucost` less than `5` shillings in `Kenya`, replace them to missing

In [78]:
def replace_ucost_based_on_country(df):
    """
    Replace ucost with NaN based on specific conditions for each country.
    
    Parameters:
    df (pd.DataFrame): The input DataFrame with columns ['hh_id', 'country', 'Product', 'consumption', 'quantity', 'ucost', 'ucode'].
    
    Returns:
    pd.DataFrame: The modified DataFrame with ucost set to NaN based on specified conditions for each country.
    """
    df_copy = df.copy()

    # Convert ucost column to float type to handle NaN values
    df_copy['ucost'] = df_copy['ucost'].astype(float)

    # Replace ucost with NaN for values less than 100 in Uganda
    uganda_condition = (df_copy['country'] == 'Uganda') & (df_copy['ucost'] < 100)
    df_copy.loc[uganda_condition, 'ucost'] = np.nan

    # Replace ucost with NaN for values less than 5 in Kenya
    kenya_condition = (df_copy['country'] == 'Kenya') & (df_copy['ucost'] < 5)
    df_copy.loc[kenya_condition, 'ucost'] = np.nan

    return df_copy

# Apply the function to Dataset1_clean_long_format_modified
Dataset1_clean_in_long_format_modified_adjusted_ucost_based_on_country = replace_ucost_based_on_country(Dataset1_clean_in_long_format_modified)

# Save the result to a CSV file
# Dataset1_clean_in_long_format_modified_adjusted_ucost_based_on_country.to_csv("Dataset1_clean_in_long_format_modified_adjusted_ucost_based_on_country.csv", index=False)

# Preview the result
Dataset1_clean_in_long_format_modified_adjusted_ucost_based_on_country.head()

hh_id country Product consumption  quantity   ucost     ucode
0  173595  Uganda    rice          No       0.0     NaN       NaN
1  173572  Uganda    rice         Yes       8.0  5000.0  Kilogram
2  174305  Uganda    rice          No       0.0     NaN       NaN
3  174401  Uganda    rice          No       0.0     NaN       NaN
4  175138  Uganda    rice         Yes       2.0  5000.0  Kilogram

### Explanation 3(c) & 3(d)
- Creates a copy of the DataFrame to avoid modifying the original data.
  - Converts the `ucost` column to `float` to handle `NaN` values.
  - Defines conditions for `Uganda` and `Kenya` based on the `country` and the `ucost` value.
  - Replaces `ucost` with `NaN` for values `less than 100 `in `Uganda`.
  - Replaces `ucost` with `NaN` for values `less than 5` in `Kenya`.

### Test 3(c) & 3(d)

In [79]:
# Define a list of hh_ids to filter for
test_hh_id_list = ["173595"]
test_hh_id_list_df = Dataset1_clean_in_long_format_modified_adjusted_ucost_based_on_country[ (Dataset1_clean_in_long_format_modified_adjusted_ucost_based_on_country['hh_id'] == test_hh_id_list[0])]
print(test_hh_id_list_df.shape)
test_hh_id_list_df

(36, 7)


hh_id country        Product consumption  quantity    ucost   ucode
0      173595  Uganda           rice          No       0.0      NaN     NaN
2496   173595  Uganda     maizeflour          No       0.0      NaN     NaN
4992   173595  Uganda      maizecobs          No       0.0      NaN     NaN
7488   173595  Uganda         millet          No       0.0      NaN     NaN
9984   173595  Uganda        sorghum          No       0.0      NaN     NaN
12480  173595  Uganda        matooke          No       0.0      NaN     NaN
14976  173595  Uganda  irishpotatoes          No       0.0      NaN     NaN
17472  173595  Uganda  sweetpotatoes         Yes       NaN      NaN   Basin
19968  173595  Uganda        cassava         Yes       1.0  25000.0   Basin
22464  173595  Uganda           yams          No       0.0      NaN     NaN
24960  173595  Uganda        pumpkin          No       0.0      NaN     NaN
27456  173595  Uganda        carrots          No       0.0      NaN     NaN
29952  173595  Uganda        cabbage          No       0.0      NaN     NaN
32448  173595  Uganda    localgreens         Yes       4.0    500.0    Heap
34944  173595  Uganda       tomatoes         Yes       2.0    500.0    Heap
37440  173595  Uganda         onions         Yes       1.0    500.0    Heap
39936  173595  Uganda        mangoes          No       0.0      NaN     NaN
42432  173595  Uganda         pawpaw          No       0.0      NaN     NaN
44928  173595  Uganda      jackfruit          No       0.0      NaN     NaN
47400  173595  Uganda       avocados          No       0.0      NaN     NaN
49896  173595  Uganda   sweetbananas          No       0.0      NaN     NaN
52392  173595  Uganda  otherfruitveg          No       0.0      NaN     NaN
54888  173595  Uganda     organmeats          No       0.0      NaN     NaN
57384  173595  Uganda           meat          No       0.0      NaN     NaN
59880  173595  Uganda           fish          No       0.0      NaN     NaN
62376  173595  Uganda           eggs          No       0.0      NaN     NaN
64872  173595  Uganda          dairy          No       0.0      NaN     NaN
67368  173595  Uganda           nuts          No       0.0      NaN     NaN
69864  173595  Uganda        legumes         Yes       8.0   2000.0     Cup
72360  173595  Uganda     cookingoil         Yes       2.0    500.0  Sacket
74856  173595  Uganda          sugar          No       0.0      NaN     NaN
77352  173595  Uganda           salt         Yes       1.0    600.0  Sacket
79848  173595  Uganda          royco          No       0.0      NaN     NaN
82344  173595  Uganda            tea          No       0.0      NaN     NaN
84840  173595  Uganda        alcohol         Yes       2.0   1000.0     Cup
87336  173595  Uganda      otherfood          No       0.0      NaN     NaN

## Question 3(e): By `product` and `country`, calculate the median `ucost` and `quantity`

In [80]:
def calculate_median_by_product_and_country(df):
    """
    Calculate the median ucost and quantity by Product and country.
    
    Parameters:
    df (pd.DataFrame): The input DataFrame with columns ['hh_id', 'country', 'Product', 'consumption', 'quantity', 'ucost', 'ucode'].
    
    Returns:
    pd.DataFrame: A DataFrame with median ucost and quantity by Product and country.
    """
    # Group by 'Product' and 'country', then calculate the median of 'ucost' and 'quantity'
    median_df = df.groupby(['Product', 'country'])[['ucost', 'quantity']].median().reset_index()
    
    return median_df

# Apply the function to Dataset1_clean_long_format_adjusted_ucost_based_on_country
median_values_df = calculate_median_by_product_and_country(Dataset1_clean_in_long_format_modified_adjusted_ucost_based_on_country)

# Save the result to a CSV file
# median_values_df.to_csv("median_ucost_quantity_by_product_country.csv", index=False)

# Preview the result
median_values_df.head()

Product country   ucost  quantity
0   alcohol   Kenya    60.0       0.0
1   alcohol  Uganda  3000.0       0.0
2  avocados   Kenya    10.0       0.0
3  avocados  Uganda   500.0       0.0
4   cabbage   Kenya    40.0       1.0

### Explanation 3(e)
- Use `groupby` method to group the data by `Product` and `country`
- Use the `median` method to calculate the `median` of `ucost` and `quantity` for each group.
- Finaly, the `reset_index` method is used to convert the grouped indices back into columns for easier viewing and saving.


## Question 3(f): Replace all `missing` values with `median` `ucost` and `median quantity`

In [81]:
def replace_nan_with_median(df):
    """
    Replace NaN values in the DataFrame with the median ucost and quantity for each Product and country.
    
    Parameters:
    df (pd.DataFrame): The input DataFrame with columns ['hh_id', 'country', 'Product', 'consumption', 'quantity', 'ucost', 'ucode'].
    
    Returns:
    pd.DataFrame: The modified DataFrame with NaN values replaced by the median ucost and quantity.
    """
    # Calculate median ucost and quantity by Product and country
    median_df = df.groupby(['Product', 'country'])[['ucost', 'quantity']].median().reset_index()

    # Merge median values back into the original DataFrame
    df_merged = df.merge(median_df, on=['Product', 'country'], suffixes=('', '_median'))

    # Replace NaN values in ucost and quantity with median values
    df_merged['ucost'] = df_merged['ucost'].fillna(df_merged['ucost_median'])
    df_merged['quantity'] = df_merged['quantity'].fillna(df_merged['quantity_median'])

    # Drop the median columns
    df_final = df_merged.drop(columns=['ucost_median', 'quantity_median'])

    return df_final

# Apply the function to Dataset1_clean_long_format_adjusted_ucost_based_on_country
Dataset1_clean_final = replace_nan_with_median(Dataset1_clean_in_long_format_modified_adjusted_ucost_based_on_country)

# Save the result to a CSV file
Dataset1_clean_final.to_csv("Dataset1_clean_final.csv", index=False)

# Preview the result
Dataset1_clean_final.head()

hh_id country Product consumption  quantity   ucost     ucode
0  173595  Uganda    rice          No       0.0  4000.0       NaN
1  173572  Uganda    rice         Yes       8.0  5000.0  Kilogram
2  174305  Uganda    rice          No       0.0  4000.0       NaN
3  174401  Uganda    rice          No       0.0  4000.0       NaN
4  175138  Uganda    rice         Yes       2.0  5000.0  Kilogram

### Explanation 3(f)
- `median_df` contains the median values for `ucost` and `quantity` by `Product` and `country`
- The original DataFrame `df` is merged with `median_df` to bring the `median` values into the original DataFrame.
- `fillna` is used to replace `NaN` values in `ucost` and `quantity` columns with the corresponding median values.
- The columns used for merging (`ucost_median` and `quantity_median`) are removed from the final DataFrame.

In [82]:
# descriptive statistics function
def dataset1_final_descriptive_statistic(df):
    # Specifying datetime_is_numeric=True adopts the future behavior of Treating datetime data as categorical rather than numeric
    dataset1_descriptive_statistic_df = df.describe(include='all')
    return dataset1_descriptive_statistic_df
 

dataset1_final_descriptive_statistic(Dataset1_clean_final)

hh_id country Product consumption      quantity          ucost  ucode
count    89808   89808   89808       89808  89808.000000   89808.000000  36969
unique    2451       2      36           2           NaN            NaN     21
top     174179  Uganda    rice          No           NaN            NaN  Whole
freq       560   47616    2496       52400           NaN            NaN   6437
mean       NaN     NaN     NaN         NaN      2.117090    1508.437188    NaN
std        NaN     NaN     NaN         NaN     48.061136    3210.153180    NaN
min        NaN     NaN     NaN         NaN      0.000000       5.000000    NaN
25%        NaN     NaN     NaN         NaN      0.000000      50.000000    NaN
50%        NaN     NaN     NaN         NaN      0.000000     455.000000    NaN
75%        NaN     NaN     NaN         NaN      1.000000    2000.000000    NaN
max        NaN     NaN     NaN         NaN  12000.000000  150001.000000    NaN