CREATE TABLE `sales-service`.kyc_requests (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `externalRefId` varchar(255) NOT NULL,
  `leadId` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `idNumber` varchar(100) NOT NULL,
  `serialNumber` varchar(100) DEFAULT NULL,
  `dob` date NOT NULL,
  `status` varchar(50) NOT NULL,
  `description` varchar(255) DEFAULT NULL COMMENT 'Managed form builder column',
  `companyRegionId` int unsigned DEFAULT NULL,
  `meta` json DEFAULT NULL,
  `createdBy` int unsigned DEFAULT NULL,
  `updatedBy` int unsigned DEFAULT NULL,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `documentType_temp` enum('NATIONAL_ID','PASSPORT','DRIVERS_LICENSE','ALIEN_ID','VOTER_ID') DEFAULT NULL,
  `documentType` enum('NATIONAL_ID','NATIONAL_ID_NO_PHOTO','ALIEN_CARD','PASSPORT','KRA_PIN','TAX_INFORMATION','GHANA_CARD','GHANA_CARD_NO_PHOTO','VOTER_ID') NOT NULL DEFAULT 'NATIONAL_ID',
  `callbackJsonBlob` json DEFAULT NULL COMMENT 'JSON blob to store callback data from KYC providers',
  `smileJobId` varchar(100) DEFAULT NULL COMMENT 'SmileID internal job reference',
  `resultCode` varchar(50) DEFAULT NULL COMMENT 'SmileID result code (e.g., 1020, 1021, 1022)',
  `resultText` varchar(100) DEFAULT NULL COMMENT 'SmileID result text (e.g., Exact Match, Partial Match, No Match)',
  `actions` json DEFAULT NULL COMMENT 'SmileID actions object with detailed field comparisons',
  `source` varchar(100) DEFAULT NULL COMMENT 'Source of verification (e.g., ID Verification)',
  `gender` varchar(255) DEFAULT NULL COMMENT 'Managed form builder column',
  `description2` varchar(255) DEFAULT NULL COMMENT 'Managed form builder column',
  `isActive` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Soft delete flag managed by the survey storage layer',
  `formId` bigint unsigned DEFAULT NULL COMMENT 'Form identifier associated with the managed record',
  `formVersion` int unsigned DEFAULT NULL COMMENT 'Published form version associated with the managed record',
  `deletedAt` datetime DEFAULT NULL COMMENT 'Timestamp when the record was soft deleted',
  `deletedBy` varchar(100) DEFAULT NULL COMMENT 'Actor that soft deleted the record',
  `archivedAt` datetime DEFAULT NULL COMMENT 'Timestamp when the record was archived',
  `archivedBy` varchar(100) DEFAULT NULL COMMENT 'Actor that archived the record',
  `lastModifiedAt` datetime DEFAULT NULL COMMENT 'Timestamp when the record was last modified by the system',
  `lastModifiedBy` varchar(100) DEFAULT NULL COMMENT 'Actor that last modified the record in managed storage',
  `is_migrated` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Indicates if the record originated from a data migration',
  PRIMARY KEY (`id`),
  KEY `kyc_requests_external_ref_id_idx` (`externalRefId`),
  KEY `kyc_requests_lead_id_idx` (`leadId`),
  CONSTRAINT `kyc_requests_leadId_fk` FOREIGN KEY (`leadId`) REFERENCES `leads` (`leadId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `chk_serial_number_uganda` CHECK (((`companyRegionId` <> 3) or ((`companyRegionId` = 3) and (`serialNumber` is not null) and (`serialNumber` <> _utf8mb4''))))
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;